#!/usr/bin/env python3
"""Pure-Python KiCad 9 project writer for the ESP32-P4 "Extreme Performance" board.

No pcbnew needed. Turns the layout plan (``layout_plan.py``) into a project
anyone can download and open::

    hardware/output/esp32p4_extreme.kicad_pcb   board, KiCad 9 file format (version 20241229)
    hardware/output/esp32p4_extreme.kicad_pro   project: net classes, patterns, HDI rules, severities
    hardware/output/esp32p4_extreme.kicad_dru   custom DRC rules (generated by layout_plan)

The board is PLACED but UNROUTED: every pad carries its net (ratsnest only),
zones are drawn but not filled (press B in KiCad), no tracks exist yet.

Footprints are the real KiCad library footprints: the ``.kicad_mod`` text of
the official KiCad 10 library (gitlab.com/kicad/libraries/kicad-footprints, tag
``layout_plan.LIBRARY_TAG`` = 10.0.6, the pad names board_spec uses), cached
under ``$KICAD_FP_CACHE`` (default ``~/.cache/esp32p4-footprints``)/10.0.6/;
missing files are downloaded unless ``--offline``. U1 is generated from
``esp32p4_pinout``.

File format: the board is written in the KiCad 9.0 format (version 20241229),
which KiCad 9 and KiCad 10 both open (KiCad 10 upgrades it on save). The only
10.0 footprint token KiCad 9 rejects, ``(duplicate_pad_numbers_are_jumpers no)``,
is dropped (it is the default).

Placing a library footprint in a board file follows what pcbnew itself writes
(checked against boards saved by KiCad 9.0.8): the footprint gets ``(at X Y o)``;
children keep footprint-relative positions; pad and text angles are absolute
(local + o on the top side); a bottom-side footprint stores its children
mirrored in local Y, with layers swapped, angles ``o - local`` and texts
``(justify mirror)``; footprint-owned zones are stored in board coordinates.

Usage::

    python3 -m hardware.pcbnew.write_kicad_pcb [-o hardware/output/esp32p4_extreme.kicad_pcb]
        [--cache DIR] [--offline] [--top-only]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from hardware.lib import board_spec as bs  # noqa: E402
from hardware.lib import esp32p4_pinout as p4  # noqa: E402
from hardware.lib import impedance as imp  # noqa: E402
from hardware.pcbnew import layout_plan as lp  # noqa: E402

FILE_VERSION = 20241229                     # KiCad 9.0 board file format
# Footprint tokens of the master (KiCad 10) library that KiCad 9.0.8 rejects. They are only
# dropped when they hold the default value ("no"), which is the case for every part used.
NEWER_THAN_9 = frozenset({"duplicate_pad_numbers_are_jumpers", "jumper_pad_groups"})
DEFAULT_OUT = REPO / "hardware" / "output" / "esp32p4_extreme.kicad_pcb"
UUID_NS = uuid.UUID("5d0f7e1c-3b0a-4c7e-9a51-e5b32f4c9a01")   # deterministic output

# ==========================================================================
# S-expressions that remember which atoms were quoted
# ==========================================================================


class Q(str):
    """A quoted string atom (everything else is a bare symbol or number)."""


_TOKEN = re.compile(r'\s*(\(|\)|"(?:[^"\\]|\\.)*"|[^\s()"]+)')


def parse(text: str) -> list:
    stack: list[list] = [[]]
    for m in _TOKEN.finditer(text):
        tok = m.group(1)
        if tok == "(":
            stack.append([])
        elif tok == ")":
            node = stack.pop()
            stack[-1].append(node)
        elif tok.startswith('"'):
            stack[-1].append(Q(re.sub(r'\\(.)', r'\1', tok[1:-1])))
        else:
            stack[-1].append(tok)
    return stack[0][0]


def num(v: float) -> str:
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def atom(a) -> str:
    if isinstance(a, Q):
        return '"' + a.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
    if isinstance(a, float):
        return num(a)
    return str(a)


def dump(node, depth: int = 0) -> str:
    """KiCad-like layout: atoms on the head line, each child list on its own line."""
    if not isinstance(node, list):
        return atom(node)
    atoms, kids = [], []
    for c in node:
        (kids if isinstance(c, list) else atoms if not kids else kids).append(c)
    head = "(" + " ".join(atom(a) for a in atoms)
    if not kids:
        return head + ")"
    if node[0] == "pts":                      # polygons: several xy per line
        xy = [dump(k) for k in kids]
        lines = [" ".join(xy[i:i + 6]) for i in range(0, len(xy), 6)]
        pad = "\t" * (depth + 1)
        return head + "\n" + "\n".join(pad + ln for ln in lines) + "\n" + "\t" * depth + ")"
    pad = "\t" * (depth + 1)
    body = "\n".join(pad + dump(k, depth + 1) for k in kids)
    return head + "\n" + body + "\n" + "\t" * depth + ")"


def child(node: list, key: str) -> list | None:
    for c in node[1:]:
        if isinstance(c, list) and c and c[0] == key:
            return c
    return None


def children(node: list, key: str) -> list[list]:
    return [c for c in node[1:] if isinstance(c, list) and c and c[0] == key]


# ==========================================================================
# Coordinates, angles, layers, uuids
# ==========================================================================

OX, OY = lp.PAGE_ORIGIN_MM


def board_xy(x: float, y: float) -> tuple[float, float]:
    return round(x + OX, 6), round(y + OY, 6)


def norm360(a: float) -> float:
    a = round(a % 360.0, 6)
    return 0.0 if a in (0.0, 360.0) else a


def norm180(a: float) -> float:
    a = norm360(a)
    return a - 360.0 if a > 180.0 else a


def swap_layer(name: str) -> str:
    if name.startswith("F."):
        return "B." + name[2:]
    if name.startswith("B."):
        return "F." + name[2:]
    return name


class Uuids:
    def __init__(self) -> None:
        self.n = 0

    def __call__(self, scope: str) -> Q:
        self.n += 1
        return Q(str(uuid.uuid5(UUID_NS, f"{scope}/{self.n}")))


# ==========================================================================
# Footprints
# ==========================================================================

def u1_mod() -> list:
    """The generated ESP32-P4 footprint as a .kicad_mod tree (footprint frame)."""
    geom = lp.u1_geometry()
    f, c = lp.U1_FAB_HALF_MM, lp.U1_COURTYARD_HALF_MM

    def line(layer, a, b, w):
        return ["fp_line", ["start", a[0], a[1]], ["end", b[0], b[1]],
                ["stroke", ["width", w], ["type", "solid"]], ["layer", Q(layer)]]

    def prop(name, value, at, layer, hide=False):
        node = ["property", Q(name), Q(value), ["at", at[0], at[1], 0.0], ["layer", Q(layer)]]
        if hide:
            node.append(["hide", "yes"])
        node.append(["effects", ["font", ["size", 1.0, 1.0], ["thickness", 0.15]]])
        return node

    t = ["footprint", Q("ESP32-P4"), ["layer", Q("F.Cu")],
         ["descr", Q(geom.description + "; solid 7.5 mm EPAD, paste 3x3 windows")],
         prop("Reference", "REF**", (0.0, -6.4), "F.SilkS"),
         prop("Value", "ESP32-P4", (0.0, 6.4), "F.Fab"),
         prop("Datasheet", "", (0.0, 0.0), "F.Fab", True),
         prop("Description", "", (0.0, 0.0), "F.Fab", True),
         prop("Height", f"{p4.HEIGHT_MAX_MM:.2f} mm", (0.0, 0.0), "F.Fab", True),
         ["attr", "smd"]]
    s, k = 5.15, 4.70
    for sx in (-1, 1):
        for sy in (-1, 1):
            t.append(line("F.SilkS", (sx * s, sy * s), (sx * k, sy * s), 0.12))
            t.append(line("F.SilkS", (sx * s, sy * s), (sx * s, sy * k), 0.12))
    t.append(["fp_circle", ["center", -5.45, -5.45], ["end", -5.33, -5.45],
              ["stroke", ["width", 0.12], ["type", "solid"]], ["fill", "yes"], ["layer", Q("F.SilkS")]])
    t.append(["fp_rect", ["start", -c, -c], ["end", c, c], ["stroke", ["width", 0.05], ["type", "solid"]],
              ["fill", "no"], ["layer", Q("F.CrtYd")]])
    fab = [(-f + 1.0, -f), (f, -f), (f, f), (-f, f), (-f, -f + 1.0)]
    t.append(["fp_poly", ["pts", *[["xy", x, y] for x, y in fab]],
              ["stroke", ["width", 0.1], ["type", "solid"]], ["fill", "no"], ["layer", Q("F.Fab")]])
    t.append(["fp_text", "user", Q("${REFERENCE}"), ["at", 0.0, 0.0, 0.0], ["layer", Q("F.Fab")],
              ["effects", ["font", ["size", 1.0, 1.0], ["thickness", 0.15]]]])
    for pad in geom.pads:
        if pad.number == "105":
            t.append(["pad", Q("105"), "smd", "rect", ["at", 0.0, 0.0], ["size", pad.sx, pad.sy],
                      ["layers", Q("F.Cu"), Q("F.Mask")], ["zone_connect", 2]])
        else:
            t.append(["pad", Q(pad.number), "smd", "oval", ["at", pad.x, pad.y], ["size", pad.sx, pad.sy],
                      ["layers", Q("F.Cu"), Q("F.Mask"), Q("F.Paste")]])
    tile, pitch = p4.EPAD_TILE_MM, p4.EPAD_TILE_PITCH_MM
    for i in (-1, 0, 1):
        for j in (-1, 0, 1):
            t.append(["pad", Q(""), "smd", "rect", ["at", i * pitch, j * pitch], ["size", tile, tile],
                      ["layers", Q("F.Paste")], ["solder_paste_margin", -0.2]])
    t.append(["model", Q(lp.U1_MODEL), ["offset", ["xyz", 0, 0, 0]], ["scale", ["xyz", 1, 1, 1]],
              ["rotate", ["xyz", 0, 0, 0]]])
    t.append(["embedded_fonts", "no"])
    return t


class FootprintSource:
    def __init__(self, cache: Path, offline: bool):
        self.cache, self.offline = cache, offline
        self._memo: dict[str, list] = {}

    def get(self, lib_id: str) -> list:
        if lib_id == lp.U1_LIB_ID:
            return u1_mod()
        if lib_id not in self._memo:
            path = lp._fetch(self.cache, lp.LIBRARY_TAG, lib_id, fetch=not self.offline)
            if path is None:
                raise FileNotFoundError(f"{lib_id}: not in {self.cache} (run without --offline)")
            self._memo[lib_id] = parse(path.read_text())
        return self._memo[lib_id]


def _f(v) -> float:
    return float(v)


class Placer:
    """Copies one library footprint tree into the board at a planned placement."""

    def __init__(self, pl: lp.Placement, comp, nets: dict[str, int], uu: Uuids):
        self.pl, self.comp, self.nets, self.uu = pl, comp, nets, uu
        self.o = norm180(pl.rot)
        self.bottom = pl.side == "B"
        self.bx, self.by = board_xy(pl.x, pl.y)
        self.pad_nets: dict[str, str] = {}       # footprint pad number -> net (set in build)

    # ---- helpers
    def angle(self, local: float) -> float:
        return norm360(self.o - local if self.bottom else self.o + local)

    def ly(self, y) -> float:
        return -_f(y) if self.bottom else _f(y)

    def layer(self, name: str) -> Q:
        return Q(swap_layer(name) if self.bottom else name)

    def xform_points(self, node: list) -> list:
        """Mirror footprint-relative points of graphics / primitives for the bottom side."""
        out = [node[0]]
        for c in node[1:]:
            if isinstance(c, list) and c and c[0] in ("start", "mid", "end", "center", "xy"):
                out.append([c[0], _f(c[1]), self.ly(c[2])])
            elif isinstance(c, list):
                out.append(self.generic(c))
            else:
                out.append(c)
        return out

    def generic(self, node: list) -> list:
        head = node[0]
        if head == "uuid":
            return ["uuid", self.uu(self.pl.ref)]
        if head == "layer":
            return ["layer", self.layer(node[1])]
        if head == "layers":
            return ["layers", *[self.layer(x) for x in node[1:]]]
        if head in ("fp_line", "fp_rect", "fp_arc", "fp_circle", "fp_poly", "fp_curve",
                    "gr_line", "gr_rect", "gr_arc", "gr_circle", "gr_poly", "gr_curve", "pts"):
            return self.xform_points(node)
        return [c if not isinstance(c, list) else self.generic(c) for c in node]

    def text(self, node: list) -> list:
        """property / fp_text: footprint-relative position, absolute angle, mirror on B."""
        out = []
        for c in node:
            if isinstance(c, list) and c and c[0] == "at":
                local = _f(c[3]) if len(c) > 3 and c[3] not in ("unlocked",) else 0.0
                extra = [x for x in c[3:] if x == "unlocked"]
                out.append(["at", _f(c[1]), self.ly(c[2]), self.angle(local), *extra])
            elif isinstance(c, list) and c and c[0] == "effects":
                eff = [x if not isinstance(x, list) else self.generic(x) for x in c]
                if self.bottom:
                    j = child(eff, "justify")
                    if j is None:
                        eff.append(["justify", "mirror"])
                    elif "mirror" in j:
                        j.remove("mirror")
                    else:
                        j.append("mirror")
                out.append(eff)
            elif isinstance(c, list):
                out.append(self.generic(c))
            else:
                out.append(c)
        return out

    def pad(self, node: list) -> list:
        out = []
        number = node[1]
        for c in node:
            if isinstance(c, list) and c and c[0] == "at":
                local = _f(c[3]) if len(c) > 3 else 0.0
                a = self.angle(local)
                out.append(["at", _f(c[1]), self.ly(c[2])] + ([a] if a else []))
            elif isinstance(c, list) and c and c[0] == "primitives":
                out.append(self.generic(c))
            elif isinstance(c, list) and c and c[0] == "drill":
                d = [x if not (isinstance(x, list) and x[0] == "offset")
                     else ["offset", _f(x[1]), self.ly(x[2])] for x in c]
                out.append(d)
            elif isinstance(c, list) and c and c[0] in ("net", "uuid"):
                continue                              # re-added below
            elif isinstance(c, list):
                out.append(self.generic(c))
            else:
                out.append(c)
        net = self.pad_nets.get(number)
        if net is not None:
            out.append(["net", self.nets[net], Q(net)])
        out.append(["uuid", self.uu(self.pl.ref)])
        return out

    def zone(self, node: list) -> list:
        """Footprint-owned zones are stored in board coordinates."""
        def xy(c):
            x, y = lp.to_board(_f(c[1]), _f(c[2]), self.pl.x, self.pl.y, self.pl.rot, self.pl.side)
            bx, by = board_xy(x, y)
            return ["xy", bx, by]

        def walk(n):
            if not isinstance(n, list):
                return n
            if n and n[0] == "xy":
                return xy(n)
            if n and n[0] in ("uuid", "layer", "layers"):
                return self.generic(n)
            return [walk(c) for c in n]
        return walk(node)

    # ---- the footprint
    def build(self, src: list) -> list:
        pl, comp = self.pl, self.comp
        numbers = [c[1] for c in children(src, "pad")]
        if comp:
            mapping, _ = lp.map_pads(comp, list(numbers))
            for spec_pad, net in comp.conns.items():
                for fp_pad in mapping.get(spec_pad, ()):
                    self.pad_nets[fp_pad] = net
        lib_id = pl.lib_id
        at = ["at", self.bx, self.by] + ([self.o] if self.o else [])
        fp = ["footprint", Q(lib_id), ["layer", Q("B.Cu" if self.bottom else "F.Cu")],
              ["uuid", self.uu(pl.ref)], at]
        value = comp.value if comp else ("Fiducial" if pl.ref.startswith("FID") else src[1])
        have_attr = False
        for c in src[2:]:
            if not isinstance(c, list):
                continue
            head = c[0]
            if head in ("version", "generator", "generator_version", "layer", "uuid", "at"):
                continue
            if head in NEWER_THAN_9:          # KiCad 10 library syntax, not in the 9.0 format
                if c[1:] not in (["no"], []):
                    raise ValueError(f"{pl.lib_id}: ({head} {c[1:]}) cannot be expressed in KiCad 9")
                continue
            if head == "property":
                name = c[1]
                node = self.text(c)
                if name == "Reference":
                    node[2] = Q(pl.ref)
                    if not pl.ref_on_silk:
                        lay = child(node, "layer")
                        lay[1] = Q("B.Fab" if self.bottom else "F.Fab")
                    elif pl.ref_xy:                   # planned, pad-free, upright position
                        lx, ly = lp.rotate(pl.ref_xy[0] - pl.x, pl.ref_xy[1] - pl.y, -pl.rot)
                        at = child(node, "at")
                        at[1:] = [round(lx, 6), round(ly, 6), 0.0]
                        font = child(child(node, "effects"), "font")
                        font[:] = ["font", ["size", pl.ref_size, pl.ref_size],
                                   ["thickness", round(0.15 * pl.ref_size, 4)]]
                elif name == "Value":
                    node[2] = Q(value)
                fp.append(node)
                continue
            if head == "attr":
                attr = list(c)
                if comp and comp.dnp and "dnp" not in attr:
                    attr.append("dnp")
                if pl.ref.startswith("FID") and "exclude_from_bom" not in attr:
                    attr.append("exclude_from_bom")
                fp.append(attr)
                have_attr = True
                self._extra_properties(fp)
                continue
            if head == "fp_text":
                fp.append(self.text(c))
            elif head == "pad":
                fp.append(self.pad(c))
            elif head == "zone":
                fp.append(self.zone(c))
            elif head == "model":
                fp.append(c)
            else:
                fp.append(self.generic(c))
        if not have_attr:
            self._extra_properties(fp)
        return fp

    def _extra_properties(self, fp: list) -> None:
        comp = self.comp
        if not comp:
            return
        fields = [("MPN", comp.part.mpn), ("Manufacturer", comp.part.manufacturer),
                  ("LCSC", comp.part.lcsc)]
        for name, value in fields:
            if not value:
                continue
            fp.append(["property", Q(name), Q(value), ["at", 0.0, 0.0, self.angle(0.0)],
                       ["layer", Q("B.Fab" if self.bottom else "F.Fab")], ["hide", "yes"],
                       ["uuid", self.uu(self.pl.ref)],
                       ["effects", ["font", ["size", 1.0, 1.0], ["thickness", 0.15]]]
                       + ([["justify", "mirror"]] if self.bottom else [])])


# ==========================================================================
# Board
# ==========================================================================

LAYER_TABLE = [
    (0, "F.Cu", "signal", lp.LAYERS["F.Cu"]), (4, "In1.Cu", "power", lp.LAYERS["In1.Cu"]),
    (6, "In2.Cu", "power", lp.LAYERS["In2.Cu"]), (2, "B.Cu", "signal", lp.LAYERS["B.Cu"]),
    (9, "F.Adhes", "user", "F.Adhesive"), (11, "B.Adhes", "user", "B.Adhesive"),
    (13, "F.Paste", "user", None), (15, "B.Paste", "user", None),
    (5, "F.SilkS", "user", "F.Silkscreen"), (7, "B.SilkS", "user", "B.Silkscreen"),
    (1, "F.Mask", "user", None), (3, "B.Mask", "user", None),
    (17, "Dwgs.User", "user", "User.Drawings"), (19, "Cmts.User", "user", "User.Comments"),
    (21, "Eco1.User", "user", "User.Eco1"), (23, "Eco2.User", "user", "User.Eco2"),
    (25, "Edge.Cuts", "user", None), (27, "Margin", "user", None),
    (31, "F.CrtYd", "user", "F.Courtyard"), (29, "B.CrtYd", "user", "B.Courtyard"),
    (35, "F.Fab", "user", None), (33, "B.Fab", "user", None),
    (39, "User.1", "user", lp.USER_LAYERS["User.1"]), (41, "User.2", "user", lp.USER_LAYERS["User.2"]),
]

PLOT_PARAMS = [
    ["layerselection", "0x00000000_00000000_55555555_5755f5ff"],
    ["plot_on_all_layers_selection", "0x00000000_00000000_00000000_00000000"],
    ["disableapertmacros", "no"], ["usegerberextensions", "no"], ["usegerberattributes", "yes"],
    ["usegerberadvancedattributes", "yes"], ["creategerberjobfile", "yes"],
    ["dashed_line_dash_ratio", "12.000000"], ["dashed_line_gap_ratio", "3.000000"],
    ["svgprecision", 4], ["plotframeref", "no"], ["mode", 1], ["useauxorigin", "yes"],
    ["hpglpennumber", 1], ["hpglpenspeed", 20], ["hpglpendiameter", "15.000000"],
    ["pdf_front_fp_property_popups", "yes"], ["pdf_back_fp_property_popups", "yes"],
    ["pdf_metadata", "yes"], ["pdf_single_document", "no"], ["dxfpolygonmode", "yes"],
    ["dxfimperialunits", "yes"], ["dxfusepcbnewfont", "yes"], ["psnegative", "no"],
    ["psa4output", "no"], ["plot_black_and_white", "yes"], ["sketchpadsonfab", "no"],
    ["plotpadnumbers", "no"], ["hidednponfab", "no"], ["sketchdnponfab", "yes"],
    ["crossoutdnponfab", "yes"], ["subtractmaskfromsilk", "no"], ["outputformat", 1],
    ["mirror", "no"], ["drillshape", 1], ["scaleselection", 1], ["outputdirectory", Q("")],
]


def stackup() -> list:
    """Physical stack-up from impedance.STACKUP (1.6 mm, 1+2+1 HDI)."""
    s = ["stackup", ["layer", Q("F.SilkS"), ["type", Q("Top Silk Screen")]],
         ["layer", Q("F.Paste"), ["type", Q("Top Solder Paste")]],
         ["layer", Q("F.Mask"), ["type", Q("Top Solder Mask")]]]
    n = 0
    for layer in imp.STACKUP:
        if layer.kind == "copper":
            s.append(["layer", Q(layer.name), ["type", Q("copper")], ["thickness", layer.thickness_mm]])
        else:
            n += 1
            kind = "core" if "core" in layer.material.lower() else "prepreg"
            s.append(["layer", Q(f"dielectric {n}"), ["type", Q(kind)], ["thickness", layer.thickness_mm],
                      ["material", Q("FR4")], ["epsilon_r", layer.er], ["loss_tangent", 0.02]])
    s += [["layer", Q("B.Mask"), ["type", Q("Bottom Solder Mask")]],
          ["layer", Q("B.Paste"), ["type", Q("Bottom Solder Paste")]],
          ["layer", Q("B.SilkS"), ["type", Q("Bottom Silk Screen")]],
          ["copper_finish", Q("ENIG")], ["dielectric_constraints", "yes"]]
    return s


def stroke(width: float) -> list:
    return ["stroke", ["width", width], ["type", "default"]]


def board_graphics(plan: lp.Plan, uu: Uuids) -> list[list]:
    out = []
    for g in plan.graphics:
        pts = [board_xy(*p) for p in g.pts]
        if g.kind == "line":
            out.append(["gr_line", ["start", *pts[0]], ["end", *pts[1]], stroke(g.width),
                        ["layer", Q(g.layer)], ["uuid", uu("gr")]])
        elif g.kind == "arc":
            out.append(["gr_arc", ["start", *pts[0]], ["mid", *pts[1]], ["end", *pts[2]], stroke(g.width),
                        ["layer", Q(g.layer)], ["uuid", uu("gr")]])
        elif g.kind == "rect":
            out.append(["gr_rect", ["start", *pts[0]], ["end", *pts[1]], stroke(g.width),
                        ["fill", "yes" if g.filled else "no"], ["layer", Q(g.layer)], ["uuid", uu("gr")]])
        elif g.kind == "circle":
            out.append(["gr_circle", ["center", *pts[0]], ["end", *pts[1]], stroke(g.width),
                        ["fill", "no"], ["layer", Q(g.layer)], ["uuid", uu("gr")]])
        elif g.kind == "text":
            out.append(["gr_text", Q(g.text), ["at", *pts[0], 0.0], ["layer", Q(g.layer)],
                        ["uuid", uu("gr")], ["effects", ["font", ["size", 1.0, 1.0], ["thickness", 0.15]]]])
    for t in plan.silk:
        out.append(["gr_text", Q(t.text), ["at", *board_xy(t.x, t.y), t.angle], ["layer", Q(t.layer)],
                    ["uuid", uu("silk")],
                    ["effects", ["font", ["size", t.size, t.glyph_width], ["thickness", t.thickness]]]])   # (size H W)
    return out


def board_zones(plan: lp.Plan, nets: dict[str, int], uu: Uuids) -> list[list]:
    out = []
    for z in plan.zones:
        layers = ["layer", Q(z.layers[0])] if len(z.layers) == 1 else ["layers", *[Q(x) for x in z.layers]]
        pts = ["pts", *[["xy", *board_xy(x, y)] for x, y in z.polygon]]
        if z.rule_area:
            ko = lambda k: "not_allowed" if k in z.keepout else "allowed"  # noqa: E731
            out.append(["zone", ["net", 0], ["net_name", Q("")], layers, ["uuid", uu("zone")],
                        ["name", Q(z.name)], ["hatch", "edge", 0.5], ["connect_pads", ["clearance", 0]],
                        ["min_thickness", 0.25], ["filled_areas_thickness", "no"],
                        ["keepout", ["tracks", ko("tracks")], ["vias", ko("vias")], ["pads", ko("pads")],
                         ["copperpour", ko("pours")], ["footprints", ko("footprints")]],
                        ["placement", ["enabled", "no"], ["sheetname", Q("")]],
                        ["fill", ["thermal_gap", 0.5], ["thermal_bridge_width", 0.5]], ["polygon", pts]])
            continue
        zone = ["zone", ["net", nets[z.net]], ["net_name", Q(z.net)], layers, ["uuid", uu("zone")],
                ["name", Q(z.name)], ["hatch", "edge", 0.5]]
        if z.priority:
            zone.append(["priority", z.priority])
        connect = ["connect_pads", "yes"] if z.connection == "solid" else ["connect_pads"]
        zone += [connect + [["clearance", lp.ZONE_CLEARANCE_MM]], ["min_thickness", lp.ZONE_MIN_WIDTH_MM],
                 ["filled_areas_thickness", "no"],
                 ["fill", ["thermal_gap", 0.2], ["thermal_bridge_width", 0.25]], ["polygon", pts]]
        out.append(zone)
    return out


def build_board(plan: lp.Plan, src: FootprintSource) -> tuple[str, dict]:
    uu = Uuids()
    comps = {c.ref: c for c in bs.COMPONENTS}
    net_names = sorted(bs.nets())
    nets = {name: i for i, name in enumerate(net_names, 1)}
    ox, oy = board_xy(0.0, 0.0)
    r = lp.DESIGN_RULES
    n_b = sum(1 for p in plan.placements.values() if p.side == "B")
    board = [
        "kicad_pcb", ["version", FILE_VERSION], ["generator", Q("esp32p4_write_kicad_pcb")],
        ["generator_version", Q("9.0")],
        ["general", ["thickness", r["board_thickness"]], ["legacy_teardrops", "no"]],
        ["paper", Q("A4")],
        ["title_block", ["title", Q("ESP32-P4 Extreme Performance")], ["rev", Q("A")],
         ["company", Q("github.com/Andreuxxx1977/esp32-p4 -- CERN-OHL-P-2.0")],
         ["comment", 1, Q("PLACED BUT UNROUTED: ratsnest only, zones unfilled (press B), no tracks.")],
         ["comment", 2, Q("Generated by hardware/pcbnew/write_kicad_pcb.py from hardware/lib/board_spec.py.")],
         ["comment", 3, Q(f"Design origin = SoC centre = aux/grid origin; {n_b} parts on B.Cu.")],
         ["comment", 4, Q("Stack-up: 4L 1.6 mm HDI 1+2+1 (see hardware/lib/impedance.py).")]],
        ["layers", *[[i, Q(n), t] + ([Q(u)] if u else []) for i, n, t, u in LAYER_TABLE]],
        ["setup", stackup(), ["pad_to_mask_clearance", 0],
         ["allow_soldermask_bridges_in_footprints", "no"], ["tenting", "front", "back"],
         ["aux_axis_origin", ox, oy], ["grid_origin", ox, oy], ["pcbplotparams", *PLOT_PARAMS]],
        ["net", 0, Q("")], *[["net", i, Q(n)] for n, i in nets.items()],
    ]
    stats = {"footprints": 0, "pads_with_net": 0}
    for ref in sorted(plan.placements, key=lp.comp_sort_key):
        pl = plan.placements[ref]
        placer = Placer(pl, comps.get(ref), nets, uu)
        fp = placer.build(src.get(pl.lib_id))
        board.append(fp)
        stats["footprints"] += 1
        stats["pads_with_net"] += sum(1 for p in children(fp, "pad") if child(p, "net"))
    board += board_graphics(plan, uu)
    for v in plan.vias:
        board.append(["via", ["at", *board_xy(v.x, v.y)], ["size", v.diameter], ["drill", v.drill],
                      ["layers", Q("F.Cu"), Q("B.Cu")], ["net", nets[v.net]], ["uuid", uu("via")]])
    board += board_zones(plan, nets, uu)
    board.append(["embedded_fonts", "no"])
    return dump(board) + "\n", stats


# ==========================================================================
# Project file
# ==========================================================================

RULE_SEVERITIES = {   # KiCad 9.0.8 defaults (as written by pcbnew), unchanged except noted
    "annular_width": "error", "clearance": "error", "connection_width": "warning",
    "copper_edge_clearance": "error", "copper_sliver": "warning", "courtyards_overlap": "error",
    "creepage": "error", "diff_pair_gap_out_of_range": "error",
    "diff_pair_uncoupled_length_too_long": "error", "drill_out_of_range": "error",
    "duplicate_footprints": "warning", "extra_footprint": "warning", "footprint": "error",
    "footprint_filters_mismatch": "ignore", "footprint_symbol_mismatch": "warning",
    "footprint_type_mismatch": "ignore", "hole_clearance": "error", "hole_to_hole": "warning",
    "holes_co_located": "warning", "invalid_outline": "error", "isolated_copper": "warning",
    "item_on_disabled_layer": "error", "items_not_allowed": "error", "length_out_of_range": "error",
    "lib_footprint_issues": "warning", "lib_footprint_mismatch": "warning",
    "malformed_courtyard": "error", "microvia_drill_out_of_range": "error",
    "mirrored_text_on_front_layer": "warning", "missing_courtyard": "ignore",
    "missing_footprint": "warning", "net_conflict": "warning",
    "nonmirrored_text_on_back_layer": "warning", "npth_inside_courtyard": "ignore",
    "padstack": "warning", "pth_inside_courtyard": "ignore", "shorting_items": "error",
    "silk_edge_clearance": "warning", "silk_over_copper": "warning", "silk_overlap": "warning",
    "skew_out_of_range": "error", "solder_mask_bridge": "error", "starved_thermal": "error",
    "text_height": "warning", "text_on_edge_cuts": "error", "text_thickness": "warning",
    "through_hole_pad_without_hole": "error", "too_many_vias": "error", "track_angle": "error",
    "track_dangling": "warning", "track_segment_length": "error", "track_width": "error",
    "tracks_crossing": "error", "unconnected_items": "error", "unresolved_variable": "error",
    "via_dangling": "warning", "zones_intersect": "error",
}


def project(plan: lp.Plan, name: str) -> dict:
    r = lp.DESIGN_RULES
    classes = []
    for prio, nc in enumerate(plan.netclasses):
        classes.append({
            "bus_width": 12, "clearance": nc.clearance,
            "diff_pair_gap": nc.dp_gap or 0.25, "diff_pair_via_gap": 0.25,
            "diff_pair_width": nc.dp_width or 0.2, "line_style": 0,
            "microvia_diameter": nc.uvia_diameter, "microvia_drill": nc.uvia_drill, "name": nc.name,
            "pcb_color": "rgba(0, 0, 0, 0.000)",
            "priority": 2147483647 if nc.name == "Default" else prio,
            "schematic_color": "rgba(0, 0, 0, 0.000)", "track_width": nc.track_width,
            "via_diameter": nc.via_diameter, "via_drill": nc.via_drill, "wire_width": 6})
    return {
        "board": {"design_settings": {
            "meta": {"version": 2},
            "rules": {"max_error": 0.005, "min_clearance": r["min_clearance"], "min_connection": 0.0,
                      "min_copper_edge_clearance": r["copper_edge"], "min_hole_clearance": r["hole_clearance"],
                      "min_hole_to_hole": r["hole_to_hole"], "min_microvia_diameter": r["uvia_diameter"],
                      "min_microvia_drill": r["uvia_drill"], "min_resolved_spokes": 2,
                      "min_silk_clearance": 0.0, "min_text_height": 0.8, "min_text_thickness": 0.08,
                      "min_through_hole_diameter": r["via_drill"], "min_track_width": r["min_track"],
                      "min_via_annular_width": r["min_annular"], "min_via_diameter": r["via_diameter"],
                      "solder_mask_to_copper_clearance": 0.0, "use_height_for_length_calcs": True,
                      "allow_microvias": True, "allow_blind_buried_vias": True},
            "rule_severities": RULE_SEVERITIES,
            "track_widths": [0.0] + sorted({nc.track_width for nc in plan.netclasses}),
            "via_dimensions": [{"diameter": 0.0, "drill": 0.0},
                               {"diameter": r["via_diameter"], "drill": r["via_drill"]},
                               {"diameter": r["uvia_diameter"], "drill": r["uvia_drill"]}],
            "diff_pair_dimensions": [{"gap": 0.0, "via_gap": 0.0, "width": 0.0}] + [
                {"gap": nc.dp_gap, "via_gap": 0.25, "width": nc.dp_width}
                for nc in plan.netclasses if nc.dp_gap]}},
        "boards": [], "libraries": {"pinned_footprint_libs": [], "pinned_symbol_libs": []},
        "meta": {"filename": f"{name}.kicad_pro", "version": 3},
        "net_settings": {"classes": classes, "meta": {"version": 4}, "net_colors": None,
                         "netclass_assignments": None,
                         "netclass_patterns": [{"netclass": cls, "pattern": net}
                                               for net, cls in plan.net_assignments.items()]},
        "pcbnew": {"last_paths": {}, "page_layout_descr_file": ""},
        "sheets": [], "text_variables": {},
    }


# ==========================================================================
# Driver
# ==========================================================================

def write(out: Path = DEFAULT_OUT, cache: Path = lp.DEFAULT_CACHE, offline: bool = False,
          allow_bottom: bool = True) -> dict:
    plan = lp.build_plan(allow_bottom=allow_bottom)
    problems = lp.validate(plan)
    if problems:
        raise SystemExit("layout plan has problems:\n  " + "\n  ".join(problems))
    text, stats = build_board(plan, FootprintSource(cache, offline))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    out.with_suffix(".kicad_pro").write_text(json.dumps(project(plan, out.stem), indent=2) + "\n")
    out.with_suffix(".kicad_dru").write_text(lp.dru_text(plan))
    stats.update(board=str(out), bytes=len(text), nets=len(bs.nets()), vias=len(plan.vias),
                 zones=len(plan.zones), silk=len(plan.silk))
    return stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Write the placed (unrouted) KiCad 9 project.")
    ap.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--cache", type=Path, default=lp.DEFAULT_CACHE,
                    help="footprint cache ($KICAD_FP_CACHE, default ~/.cache/esp32p4-footprints)")
    ap.add_argument("--offline", action="store_true", help="never download footprints")
    ap.add_argument("--top-only", action="store_true", help="never place SoC-ring parts on B.Cu")
    args = ap.parse_args(argv)
    stats = write(args.output, args.cache, args.offline, not args.top_only)
    print(json.dumps(stats, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
