"""Generate the TASK 1 / TASK 2 / TASK 4 documents and the PCBWay BOM from ``hardware.lib``.

Run from the repository root::

    python3 -m tools.gen_docs            # (re)write every generated file
    python3 -m tools.gen_docs --check    # exit 1 if any generated file is stale

Outputs (all fully generated, deterministic, no timestamps):

* ``docs/TASK1_pinout.md``               architecture, GPIO table, conflict analysis, routing rules
* ``docs/TASK2_mechanical_thermal.md``   heat paths, thermal estimate, coordinates, collision check, fan control
* ``docs/TASK4_bom_pcbway.md``           PCBWay turnkey BOM + ordering notes
* ``hardware/output/bom_pcbway.csv``     the same BOM rows as CSV

Every number, reference designator, net, coordinate and part that appears in the documents is
read from ``hardware/lib`` at run time. The only literals in this file are (a) layout-guideline
limits quoted from the Espressif ESP32-P4 hardware design guidelines, (b) datasheet constants
confirmed by the component-verification pass (buck VFB) and (c) the thermal-model assumptions in
the ``THERMAL ASSUMPTIONS`` block, each of which is printed in the document next to its result.
"""

from __future__ import annotations

import argparse
import csv
import io
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from hardware.lib import board_spec as bs
from hardware.lib import esp32p4_pinout as p4
from hardware.lib import impedance as imp

ROOT = Path(__file__).resolve().parents[1]
TASK1_MD = ROOT / "docs" / "TASK1_pinout.md"
TASK2_MD = ROOT / "docs" / "TASK2_mechanical_thermal.md"
TASK4_MD = ROOT / "docs" / "TASK4_bom_pcbway.md"
BOM_CSV = ROOT / "hardware" / "output" / "bom_pcbway.csv"

BANNER = ("<!-- GENERATED by tools/gen_docs.py from hardware/lib/*.py -- do not edit by hand. "
          "Regenerate: python3 -m tools.gen_docs -->")

# ---------------------------------------------------------------------------
# Espressif ESP32-P4 hardware design guidelines (PCB layout chapter) -- limits
# ---------------------------------------------------------------------------
MIL_MM = 0.0254
USB_Z_TOL = 0.10            # 90 ohm +/-10 %
MIPI_Z_TOL = 0.10           # 100 ohm +/-10 %
MIPI_INTRA_MIL = 10         # P/N skew inside a lane
MIPI_INTER_MIL = 30         # lane-to-lane (incl. clock) skew
SDIO_SKEW_MIL = 50          # CMD/DATA within +/-50 mil of CLK
SDIO_TOTAL_MIL = 2000       # total SDIO trace length
XTAL_MIN_MM = 4.5           # crystal body >= 4.5 mm from the SoC clock pads
SE_Z_TOL = 0.10             # generic +/-10 % fab tolerance used for the SE/ETH classes

# Buck feedback references (datasheet values, confirmed in docs/component_verification.md).
BUCK_VFB = {"TPS62130": 0.8, "TLV62569": 0.6}

# ---------------------------------------------------------------------------
# THERMAL ASSUMPTIONS -- engineering estimates, each is printed in TASK 2
# ---------------------------------------------------------------------------
K_CU = 385.0                 # W/m.K, copper
PLATING_UM = 25.0            # via barrel plating (IPC-6012 class 3 average -- call out on the order)
THETA_JC_TOP = 12.0          # K/W, die -> mould-compound top (estimate, NOT an Espressif figure)
THETA_JC_BOT = 2.0           # K/W, die -> EPAD (estimate, NOT an Espressif figure)
K_TIM = 3.0                  # W/m.K, phase-change pad after reflow of the TIM (datasheet-class value)
SOLDER_UM = 50.0             # EPAD solder bond line
K_SOLDER = 58.0              # W/m.K, SAC305
PASTE_COVERAGE = 0.6         # EPAD paste coverage (tiled stencil)
H_NAT = 12.0                 # W/m2.K, natural convection + radiation (black anodised)
H_FAN = 60.0                 # W/m2.K, impinging flow from a 25-30 mm 5 V fan into pin fins
FIN_EFF_NAT = 0.95
FIN_EFF_FAN = 0.85
PIN_GRID = 6                 # 6 x 6 square pin fins (radial exhaust needs pins, not plates)
PIN_SIDE_MM = 2.0
BASE_T_MM = 2.0
BOARD_SPREAD_EFF = 0.30      # fraction of the 110 x 80 mm board that is effectively isothermal
H_BOARD_EXHAUST = 25.0       # W/m2.K, board top surface in the fan exhaust
T_AMB = 40.0                 # degC, enclosure ambient used for the Tj estimate
SPREADER_MM = bs.BOTTOM_SPREADER_MM        # B.Cu GND spreader copper under U1
WINDOW_MM = bs.BOTTOM_THERMAL_WINDOW_MM     # exposed (mask-free) part of it: the via field
GAP_PAD_MM, K_GAP_PAD = 1.0, 3.0   # optional bottom gap pad to a chassis
POWER_ESTIMATE = (
    # contributor, low W, high W, basis
    ("VDD_HP domain: 2x RISC-V @ 400 MHz, L2MEM, ISP / H.264 / PPA / 2D-DMA", 0.35, 0.90,
     "assumed 0.3-0.75 A on the VDD_HP rail"),
    ("In-package 32 MB PSRAM + flash IO via on-chip LDOs (LDO drop dissipated in the package)",
     0.10, 0.35, "assumed 30-100 mA from 3.3 V"),
    ("MIPI DSI + CSI D-PHY, USB 2.0 HS PHY, analog, IO ring", 0.10, 0.30,
     "assumed 30-90 mA from 3.3 V"),
)
P_DESIGN_W = 2.0             # thermal design point (margin over the estimate)
M3_KEEPOUT_R = 3.5           # M3 washer (DIN 125, 7 mm OD) -- used for the board-hole check only
FIDUCIAL_CLEAR_MM = 3.0      # recommended copper/part-free radius around a 1 mm fiducial

# Fan curve suggestion (die temperature from the P4 internal sensor) -- starting point only.
FAN_CURVE = ((None, 45.0, (0, 0)), (45.0, 55.0, (30, 30)), (55.0, 75.0, (30, 100)), (75.0, None, (100, 100)))
FAN_HYST_K = 3.0

GND = bs.GND
COMP = {c.ref: c for c in bs.COMPONENTS}
NETS = bs.nets()
U1 = bs.U1
USE = {u.gpio: u for u in bs.GPIO_MAP}
USE_BY_NET = {u.net: u for u in bs.GPIO_MAP}
PAD_BY_NAME = {name: pad for pad, name, _ in p4.PADS}
KO = bs.KEEPOUT_HALF
R_HOLE = bs.HEATSINK_HOLE_KEEPOUT_R
HS_FLAG_MM = R_HOLE + 1.0


# ===========================================================================
# Formatting helpers
# ===========================================================================

def natural_key(s: str) -> list:
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", s)]


def f(x: float, nd: int = 2) -> str:
    v = round(float(x), nd)
    if v == 0:
        v = 0.0
    return f"{v:.{nd}f}"


def xy(p: tuple[float, float], nd: int = 1) -> str:
    return f"({f(p[0], nd)}, {f(p[1], nd)})"


def esc(s: object) -> str:
    """Escape a plain-text table cell (GFM: '|' splits cells, '~' strikes through)."""
    return str(s).replace("|", "\\|").replace("~", "\\~").replace("\n", " ")


def code(s: object) -> str:
    return "`" + str(s).replace("|", "\\|") + "`"


def md_table(headers: list[str], rows: list[list[str]], align: str | None = None) -> str:
    align = align or "l" * len(headers)
    sep = {"l": "---", "r": "---:", "c": ":---:"}
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join(sep[a] for a in align) + " |"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def refs_join(refs) -> str:
    return ", ".join(sorted(refs, key=natural_key))


def ref_ranges(refs) -> str:
    """['R12','R13','R14','R20'] -> 'R12-R14, R20'."""
    by_pfx: dict[str, list[int]] = defaultdict(list)
    other = []
    for r in refs:
        m = re.fullmatch(r"([A-Z_]+?)(\d+)", r)
        if m:
            by_pfx[m.group(1)].append(int(m.group(2)))
        else:
            other.append(r)
    out = []
    for pfx in sorted(by_pfx):
        for chunk in ranges(by_pfx[pfx]).split(", "):
            a, _, b = chunk.partition("-")
            out.append(f"{pfx}{a}" + (f"-{pfx}{b}" if b else ""))
    return ", ".join(out + sorted(other, key=natural_key)) or "-"


def ranges(nums) -> str:
    """[1,2,3,5] -> '1-3, 5'."""
    nums = sorted(set(int(n) for n in nums))
    out, i = [], 0
    while i < len(nums):
        j = i
        while j + 1 < len(nums) and nums[j + 1] == nums[j] + 1:
            j += 1
        out.append(str(nums[i]) if i == j else f"{nums[i]}-{nums[j]}")
        i = j + 1
    return ", ".join(out)


def status(ok: bool, warn: bool = False) -> str:
    return "OK" if ok else ("CHECK" if warn else "**FAIL**")


# ===========================================================================
# Netlist helpers (all derived from board_spec.COMPONENTS)
# ===========================================================================

def pin_name(comp: bs.Component, pad: str) -> str:
    return dict(comp.part.pins).get(pad, pad)


def net_of(comp: bs.Component, name: str) -> str | None:
    for pad, nm in comp.part.pins:
        if nm == name and pad in comp.conns:
            return comp.conns[pad]
    return None


def other_end(comp: bs.Component, pad: str) -> str | None:
    others = [n for p, n in comp.conns.items() if p != pad]
    return others[0] if len(set(others)) == 1 else None


def ohms(value: str) -> float | None:
    m = re.fullmatch(r"([0-9]*\.?[0-9]+)\s*([kKM]?)(?:R|ohm)?", value.strip())
    if not m:
        return None
    return float(m.group(1)) * {"": 1.0, "k": 1e3, "K": 1e3, "M": 1e6}[m.group(2)]


def members(net: str) -> list[tuple[bs.Component, str]]:
    return sorted(((COMP[r], p) for r, p in NETS.get(net, [])),
                  key=lambda cp: (natural_key(cp[0].ref), natural_key(cp[1])))


def two_pin(comp: bs.Component) -> bool:
    return len(set(comp.conns.values())) == 2 and len(comp.part.pad_numbers) <= 2


def _rails() -> set[str]:
    rails = {GND} | {n for n in NETS if bs.netclass_of(n) == "POWER"}
    for c in bs.COMPONENTS:
        if c.part.kind != "ic":
            continue
        for pad, net in c.conns.items():
            if re.match(r"^(VDD|VCC|VIO|AVIN|PVIN|VIN|VREGIN)", pin_name(c, pad)):
                rails.add(net)
    return rails


RAILS = _rails()


def resistors_between(a: str, b: str) -> list[bs.Component]:
    return sorted((c for c in bs.COMPONENTS if c.part.kind == "res" and set(c.conns.values()) == {a, b}),
                  key=lambda c: natural_key(c.ref))


def is_series(comp: bs.Component, limit: float = 1000.0) -> bool:
    v = ohms(comp.value)
    return comp.part.kind == "res" and two_pin(comp) and v is not None and v <= limit


def evidence(net: str) -> list[str]:
    """Pull resistors, switches and transistors on ``net`` (following one series resistor)."""
    out: list[str] = []

    def scan(n: str, via: str | None, skip: set[str]) -> None:
        for c, pad in members(n):
            if c.ref in skip or c.ref == "U1":
                continue
            dnp = " (DNP)" if c.dnp else ""
            tail = f" via {via}" if via else ""
            if c.part.kind == "res" and two_pin(c):
                other = other_end(c, pad)
                if other in RAILS:
                    out.append(f"{c.ref} {c.value}{dnp} to {other}{tail}")
                elif via is None and is_series(c):
                    scan(other, f"{c.ref} {c.value}", skip | {c.ref})
            elif c.part.kind == "sw":
                out.append(f"{c.ref} to {other_end(c, pad)}{tail}")
            elif c.part.kind == "fet":
                out.append(f"{c.ref}.{pin_name(c, pad)}{tail}")

    scan(net, None, set())
    return out


def describe(net: str, exclude: frozenset[str] = frozenset({"U1"}), depth: int = 0) -> list[str]:
    """Human-readable list of what hangs on ``net`` (one series-resistor hop is followed)."""
    items = []
    for c, pad in members(net):
        if c.ref in exclude:
            continue
        dnp = " (DNP)" if c.dnp else ""
        if c.part.kind in ("res", "cap", "fb") and two_pin(c):
            other = other_end(c, pad)
            if depth == 0 and c.part.kind == "res" and other not in RAILS and is_series(c):
                far = describe(other, exclude | {c.ref}, depth + 1)
                items.append(f"{c.ref} {c.value}{dnp} -> {code(other)} -> " + (", ".join(far) or "-"))
            else:
                items.append(f"{c.ref} {c.value}{dnp} to {code(other)}")
        else:
            pn = pin_name(c, pad)
            items.append(f"{c.ref}.{pad}" + (f" ({esc(pn)})" if pn != pad else ""))
    return items


def reach(nets, limit: float = 100.0) -> list[str]:
    """Non-passive parts on ``nets`` or one low-ohm series resistor away (U1 included)."""
    found: list[str] = []
    for n in nets:
        for c, pad in members(n):
            if c.part.kind in ("res", "cap"):
                far = other_end(c, pad) if is_series(c, limit) else None
                if far and far not in RAILS:
                    found += [c2.ref for c2, _ in members(far) if c2.part.kind not in ("res", "cap")]
            else:
                found.append(c.ref)
    return sorted(set(found), key=natural_key)


def soc_crystal() -> bs.Component | None:
    xt = [c for c in bs.COMPONENTS if c.part.kind == "xtal"]
    return next((c for c in xt if "U1" in reach(set(c.conns.values()) - {GND})), None)


def board_xy(comp: bs.Component) -> tuple[float, float] | None:
    return (comp.place.x, comp.place.y) if isinstance(comp.place, bs.Place) else None


def u1_pad_xy(pad: str) -> tuple[float, float]:
    """Pad centre in board coordinates (applies U1 placement + KiCad rotation)."""
    px, py = p4.pad_position(pad)
    pl = U1.place
    th = math.radians(pl.rot)
    return (pl.x + px * math.cos(th) + py * math.sin(th),
            pl.y - px * math.sin(th) + py * math.cos(th))


def dist(a, b) -> float:
    return math.hypot(a[0] - b[0], a[1] - b[1])


def seg_dist(p, a, b) -> float:
    ax, ay = a
    dx, dy = b[0] - ax, b[1] - ay
    L2 = dx * dx + dy * dy
    t = 0.0 if L2 == 0 else max(0.0, min(1.0, ((p[0] - ax) * dx + (p[1] - ay) * dy) / L2))
    return math.hypot(p[0] - (ax + t * dx), p[1] - (ay + t * dy))


def keepout_clearance(p) -> float:
    """Distance from a point to the heatsink keep-out square (negative = inside)."""
    dx, dy = abs(p[0]) - KO, abs(p[1]) - KO
    if dx <= 0 and dy <= 0:
        return max(dx, dy)
    return math.hypot(max(dx, 0.0), max(dy, 0.0))


def direction(p) -> str:
    ang = math.degrees(math.atan2(-p[1], p[0])) % 360     # +Y is down in KiCad
    names = ("right", "top-right", "top", "top-left", "left", "bottom-left", "bottom", "bottom-right")
    return names[int(((ang + 22.5) % 360) // 45)]


def iomux_signal(use: bs.GpioUse) -> str | None:
    hits = []
    for sig in p4.IOMUX_OPTIONS:
        aliases = {sig, sig.replace("SD0_", "SD_")}
        if use.net in aliases or re.search(rf"(?<![A-Z0-9_]){re.escape(sig)}(?![A-Z0-9_])", use.function):
            hits.append(sig)
    return hits[0] if len(hits) == 1 else None


def pad_range(spec: str) -> list[str]:
    a, _, b = spec.partition("-")
    return [str(n) for n in range(int(a), int(b or a) + 1)]


DEDICATED_GROUP = {pad: name for name, spec in p4.DEDICATED_PADS.items() for pad in pad_range(spec)}


def u1_net(pad: str) -> str | None:
    return U1.conns.get(pad)


def gpio_of_net(net: str | None) -> int | None:
    u = USE_BY_NET.get(net or "")
    return u.gpio if u else None


def verification_flags() -> list[tuple[str, str, str]]:
    """(where, item, text) for every spec string that says PENDING / verify / tune."""
    pat = re.compile(r"PENDING|UNVERIFIED|verify|to be matched|tune on first|cross-check", re.I)
    out = []
    for part in sorted(bs.PARTS.values(), key=lambda p: natural_key(p.key)):
        for field in ("pin_source", "description"):
            txt = getattr(part, field)
            if pat.search(txt):
                out.append((f"part {part.key}", field, txt))
    seen = set()
    for c in sorted(bs.COMPONENTS, key=lambda c: natural_key(c.ref)):
        if c.note and pat.search(c.note) and c.note not in seen:
            seen.add(c.note)
            refs = [d.ref for d in bs.COMPONENTS if d.note == c.note]
            out.append((refs_join(refs), "note", c.note))
    return out


# ===========================================================================
# Derived design data
# ===========================================================================

def power_tree() -> list[dict]:
    """Breadth-first walk from the USB VBUS pins through series power elements.

    Each row: {"net", "feeds": [(parent_net, via_dict)]}; source rows have no feeds.
    """
    sources = []
    for c in sorted(bs.COMPONENTS, key=lambda c: natural_key(c.ref)):
        if c.part.kind == "conn":
            for pad, nm in c.part.pins:
                if nm == "VBUS" and pad in c.conns and c.conns[pad] not in sources:
                    sources.append(c.conns[pad])
    rows = {s: {"net": s, "feeds": []} for s in sources}
    order, queue = list(sources), list(sources)
    while queue:
        net = queue.pop(0)
        edges = []
        for c, pad in members(net):
            nm = pin_name(c, pad)
            if c.dnp:
                continue
            if c.ref == "U1":
                if nm == "VDD_LDO":
                    for p2, n2 in sorted(U1.conns.items(), key=lambda kv: int(kv[0])):
                        if p4.PAD_TYPE.get(p2) == "power_out":
                            edges.append((n2, {"kind": "ldo", "refs": ["U1"],
                                               "label": f"U1 on-chip LDO {p4.PAD_NAME[p2]} (pad {p2})"}))
                continue
            if c.part.kind == "diode" and {n for _, n in c.part.pins} == {"A", "K"} and nm == "A":
                edges.append((net_of(c, "K"), {"kind": "diode", "refs": [c.ref],
                                               "label": f"{c.ref} {c.value}"}))
            elif c.part.kind == "fb" and two_pin(c):
                edges.append((other_end(c, pad), {"kind": "fb", "refs": [c.ref],
                                                  "label": f"{c.ref} {c.value}"}))
            elif c.part.kind == "res" and two_pin(c) and ohms(c.value) == 0:
                edges.append((other_end(c, pad), {"kind": "0R", "refs": [c.ref], "label": f"{c.ref} 0R"}))
            elif c.part.kind == "fet" and nm == "S" and net_of(c, "D"):
                edges.append((net_of(c, "D"), {"kind": "switch", "refs": [c.ref],
                                               "label": f"{c.ref} {c.value} load switch"}))
            elif c.part.kind == "ic" and re.match(r"^P?VIN$", nm):
                sw = net_of(c, "SW")
                ind = [d for d, _ in members(sw or "") if d.part.kind == "ind"]
                if sw and ind:
                    pad_sw = next(p for p, n in ind[0].conns.items() if n == sw)
                    edges.append((other_end(ind[0], pad_sw),
                                  {"kind": "buck", "refs": [c.ref, ind[0].ref], "ic": c,
                                   "label": f"{c.ref} {c.value} buck + {ind[0].ref} {ind[0].value}"}))
        for child, via in edges:
            if not child or child == GND or child in sources:
                continue
            if child in rows and via["kind"] != "diode":
                continue            # undirected element pointing back up the tree
            if child not in rows:
                rows[child] = {"net": child, "feeds": []}
                order.append(child)
                queue.append(child)
            if all(v["label"] != via["label"] for _, v in rows[child]["feeds"]):
                rows[child]["feeds"].append((net, via))
    return [rows[n] for n in order]


def buck_vout(ic: bs.Component, out_net: str) -> tuple[float | None, str]:
    vfb = BUCK_VFB.get(ic.value)
    fb = net_of(ic, "FB")
    top = resistors_between(out_net, fb) if fb else []
    bot = resistors_between(fb, GND) if fb else []
    if vfb is None or not top or not bot:
        return None, ""
    rt, rb = ohms(top[0].value), ohms(bot[0].value)
    v = vfb * (1 + rt / rb)
    return v, f"{f(vfb, 1)} V x (1 + {top[0].ref} {top[0].value} / {bot[0].ref} {bot[0].value})"


def rail_voltage(tree: list[dict]) -> dict[str, tuple[str, str]]:
    """net -> (short voltage, how it is set)."""
    volt: dict[str, tuple[str, str]] = {}
    for row in tree:
        net = row["net"]
        if not row["feeds"]:
            volt[net] = ("5 V", "USB VBUS")
            continue
        parent, via = row["feeds"][0]
        if via["kind"] == "buck":
            v, how = buck_vout(via["ic"], net)
            volt[net] = (f"{f(v, 2)} V", how) if v else ("see regulator", "")
        elif via["kind"] == "diode":
            refs = ", ".join(v["refs"][0] for _, v in row["feeds"])
            volt[net] = (f"VBUS - V_F", f"Schottky OR ({refs})")
        elif via["kind"] == "ldo":
            volt[net] = ("SoC LDO", "set by firmware / eFuse")
        else:
            volt[net] = (volt.get(parent, ("-", ""))[0], f"= {parent}")
    return volt


def rail_loads(net: str, exclude: set[str]) -> str:
    refs, u1pads = [], []
    for c, pad in members(net):
        if c.ref == "U1":
            u1pads.append(pad)
        elif c.part.kind not in ("res", "cap", "fb", "ind") and c.ref not in exclude and c.ref not in refs:
            refs.append(c.ref)
    parts = []
    if u1pads:
        parts.append(f"U1 pads {ranges(u1pads)}")
    parts += [f"{r} {COMP[r].value}" for r in refs]
    return ", ".join(parts) or "-"


def interface_sets() -> list[tuple[str, str, set[int], set[str]]]:
    """(label, kind, gpios, pads) for the conflict analysis."""
    def gp(pred):
        g = {u.gpio for u in bs.GPIO_MAP if pred(u)}
        return g, {p4.GPIO_PAD[x] for x in g}

    def ded(pred):
        return {pad for name, spec in p4.DEDICATED_PADS.items() if pred(name) for pad in pad_range(spec)}

    sets = []
    for label, pred in (("RMII / Ethernet", lambda u: "Ethernet" in u.block),
                        ("SDIO (microSD)", lambda u: u.block == "microSD"),
                        ("USB Serial/JTAG", lambda u: u.block == "USB-JTAG"),
                        ("UART0", lambda u: u.block == "Debug UART")):
        g, pads = gp(pred)
        sets.append((label, "GPIO", g, pads))
    for label, pred in (("MIPI DSI + CSI", lambda n: "MIPI" in n),
                        ("USB 2.0 HS", lambda n: "USB 2.0 HS" in n)):
        sets.append((label, "dedicated", set(), ded(pred)))
    for label, _, g, pads in sets:
        if not pads:
            raise SystemExit(f"gen_docs: interface set '{label}' is empty -- spec block names changed?")
    return sets


HS_IFACES = (
    ("MIPI DSI", r"^DSI_(D\d|CLK)_[PN]$"),
    ("MIPI CSI", r"^CSI_(D\d|CLK)_[PN]$"),
    ("USB 2.0 HS", r"^USBHS_D[PM]$"),
    ("USB Serial/JTAG (FS)", r"^USJ_D[PM]$"),
    ("SDIO (SDMMC slot 0)", r"^SD_(D\d|CLK|CMD)$"),
    ("RMII", r"^RMII_"),
    ("QSPI flash", r"^FLASH_"),
    ("SoC crystal", r"^XTAL_[PN]$"),
)
OFFSOC_LINKS = (   # label, net pattern, part kind of the start point
    ("Ethernet MDI (PHY -> RJ45)", r"^ETH_(TX|RX)_[PN]$", "ic"),
    ("USB FS debug (USB-C -> CP2102N)", r"^USB2_D[PM]$", "conn"),
)


def _endpoint_counts(nets: list[str]) -> Counter:
    cnt: Counter = Counter()
    for n in nets:
        for c, pad in members(n):
            if c.ref == "U1":
                continue
            if c.part.kind in ("res", "cap"):
                if is_series(c, 100.0) and other_end(c, pad) not in RAILS:
                    for c2, _ in members(other_end(c, pad)):
                        if c2.part.kind not in ("res", "cap") and c2.ref != "U1":
                            cnt[c2.ref] += 1
            else:
                cnt[c.ref] += 1
    return cnt


def _pick(cnt: Counter, need_place: bool = True) -> list[str]:
    cands = [r for r in cnt if not need_place or board_xy(COMP[r])]
    return sorted(cands, key=lambda r: (-cnt[r], COMP[r].part.kind != "conn", natural_key(r)))


def hs_links() -> list[dict]:
    out = []
    for label, pat in HS_IFACES:
        pads = sorted((p for p, n in U1.conns.items() if re.match(pat, n)), key=int)
        if not pads:
            continue
        pts = [u1_pad_xy(p) for p in pads]
        a = (sum(x for x, _ in pts) / len(pts), sum(y for _, y in pts) / len(pts))
        target = _pick(_endpoint_counts([U1.conns[p] for p in pads]))
        if not target:
            continue
        b = board_xy(COMP[target[0]])
        out.append({"label": label, "pads": pads, "a": a, "b": b, "from": "U1", "to": target[0]})
    for label, pat, start_kind in OFFSOC_LINKS:
        nets = sorted(n for n in NETS if re.match(pat, n))
        ends = sorted(_pick(_endpoint_counts(nets))[:2], key=lambda r: COMP[r].part.kind != start_kind)
        if len(ends) >= 2:
            out.append({"label": label, "pads": [], "a": board_xy(COMP[ends[0]]),
                        "b": board_xy(COMP[ends[1]]), "from": ends[0], "to": ends[1]})
    return out


def placed_parts() -> list[bs.Component]:
    return sorted((c for c in bs.COMPONENTS if isinstance(c.place, bs.Place)
                   and c.ref != "U1" and c.part.kind != "mech"), key=lambda c: natural_key(c.ref))


def near_anchor(comp: bs.Component) -> tuple[tuple[float, float], float, str] | None:
    """(anchor xy, accumulated slack mm, description) for a Near placement."""
    slack, pl, chain = 0.0, comp.place, []
    while isinstance(pl, bs.Near):
        slack += pl.max_mm
        anchor = COMP[pl.ref]
        chain.append(f"{pl.ref}" + (f".{pl.pad}" if pl.pad else ""))
        if anchor.ref == "U1" and pl.pad:
            return u1_pad_xy(pl.pad), slack, " -> ".join(chain)
        pl = anchor.place
    if isinstance(pl, bs.Place):
        return (pl.x, pl.y), slack, " -> ".join(chain)
    return None


# ===========================================================================
# Shared tables
# ===========================================================================

def stackup_table() -> str:
    rows = []
    for i, layer in enumerate(imp.STACKUP, 1):
        rows.append([str(i), esc(layer.name), layer.kind, f(layer.thickness_mm, 3),
                     esc(layer.material or "-"), f(layer.er, 1) if layer.er else "-",
                     esc(layer.function or "-")])
    rows.append(["", "**Total**", "", f"**{f(imp.BOARD_THICKNESS_MM, 3)}**", "", "", ""])
    return md_table(["#", "Layer", "Type", "Thickness (mm)", "Material", "Er", "Function"], rows,
                    "rllrlrl")


def impedance_table() -> str:
    rows = []
    for r in imp.impedance_rules():
        err = (r.achieved_ohm - r.target_ohm) / r.target_ohm * 100
        gap = f"{f(r.gap_mm, 3)} / {f(r.gap_mm / MIL_MM, 1)}" if r.gap_mm else "-"
        rows.append([code(r.netclass), f"{f(r.target_ohm, 0)} {'diff' if r.kind == 'diff' else 'SE'}",
                     f"{f(r.width_mm, 3)} / {f(r.width_mm / MIL_MM, 1)}", gap, f(r.achieved_ohm, 1),
                     f"{err:+.1f} %", esc(r.nets_hint)])
    return md_table(["Net class", "Target (ohm)", "Width mm / mil", "Gap mm / mil", "Model (ohm)",
                     "Error", "Nets"], rows, "lrrrrrl")


def rule(netclass: str) -> imp.ImpedanceRule | None:
    return next((r for r in imp.impedance_rules() if r.netclass == netclass), None)


# ===========================================================================
# TASK 1
# ===========================================================================

def _architecture() -> list[str]:
    L = []
    soc = U1.part
    n_fit = sum(1 for c in bs.COMPONENTS if not c.dnp and c.part.kind != "mech")
    L += ["## 1. Architecture", "",
          f"{soc.mpn} ({esc(soc.description)}; {esc(soc.package)}) sits at the design origin under a "
          f"{f(2 * KO, 0)} x {f(2 * KO, 0)} mm heatsink keep-out. {len(bs.COMPONENTS)} component instances "
          f"({n_fit} fitted, non-mechanical), {len(NETS)} nets, {len(bs.PARTS)} part types, "
          f"{len([l for l in imp.STACKUP if l.kind == 'copper'])}-layer {f(imp.BOARD_THICKNESS_MM, 1)} mm HDI "
          f"board, {f(bs.BOARD_OUTLINE[2] - bs.BOARD_OUTLINE[0], 0)} x "
          f"{f(bs.BOARD_OUTLINE[3] - bs.BOARD_OUTLINE[1], 0)} mm.", ""]

    # --- blocks by component group
    groups: dict[str, list[bs.Component]] = {}
    for c in bs.COMPONENTS:
        groups.setdefault(c.group, []).append(c)
    rows = []
    for g, comps in groups.items():
        key = [f"{c.ref} {esc(c.value)}" for c in comps if c.part.kind not in ("res", "cap", "mech")]
        passives = Counter(c.part.kind for c in comps if c.part.kind in ("res", "cap"))
        pas = ", ".join(f"{n} {k}" for k, n in sorted(passives.items()))
        dnp = sum(1 for c in comps if c.dnp)
        rows.append([esc(g), str(len(comps)), ", ".join(key) or "-", pas or "-", str(dnp) if dnp else "-"])
    L += ["### 1.1 Blocks (component groups in `board_spec.COMPONENTS`)", "",
          md_table(["Group", "Parts", "Active parts / connectors", "Passives", "DNP"], rows, "lrllr"), ""]

    # --- SoC resources by block
    by_block: dict[str, list[int]] = defaultdict(list)
    for u in bs.GPIO_MAP:
        by_block[u.block].append(u.gpio)
    rows = [[esc(b), ranges(g), str(len(g))] for b, g in sorted(by_block.items(), key=lambda kv: min(kv[1]))]
    rows.append(["NC (reserved)", ranges(bs.GPIO_NC), str(len(bs.GPIO_NC))])
    ded = [[esc(name), spec, esc(", ".join(sorted({u1_net(p) or '-' for p in pad_range(spec)})))]
           for name, spec in p4.DEDICATED_PADS.items()]
    L += ["### 1.2 SoC resources per block", "",
          md_table(["Block (GPIO_MAP)", "GPIOs", "Count"], rows, "llr"), "",
          md_table(["Dedicated function (DEDICATED_PADS)", "U1 pads", "Nets"], ded), ""]

    # --- power tree
    tree = power_tree()
    volt = rail_voltage(tree)
    rows = []
    for row in tree:
        feeds = row["feeds"]
        excl = {r for _, v in feeds for r in v["refs"]}
        excl |= {c.ref for c, _ in members(row["net"]) if c.part.kind == "diode"
                 and {n for _, n in c.part.pins} == {"A", "K"}}
        src = {c.ref for c, pad in members(row["net"]) if c.part.kind == "conn" and pin_name(c, pad) == "VBUS"}
        short, how = volt[row["net"]]
        rows.append([code(row["net"]),
                     ", ".join(code(p) for p, _ in feeds) or f"{refs_join(src)} VBUS pins",
                     esc(", ".join(v["label"] for _, v in feeds)) or "-",
                     esc(short + (f" ({how})" if how and not how.startswith("=") else "")),
                     esc(rail_loads(row["net"], excl | src))])
    L += ["### 1.3 Power tree (walked from the USB VBUS pins through series power elements)", "",
          md_table(["Rail", "Fed from", "Via", "Voltage", "Loads on the rail (non-passive)"], rows), ""]

    # --- clocks
    rows = []
    for c in sorted((c for c in bs.COMPONENTS if c.part.kind == "xtal"), key=lambda c: natural_key(c.ref)):
        consumers = [r for r in reach(set(c.conns.values()) - {GND})
                     if COMP[r].part.kind == "ic" and r != c.ref]
        cons = ", ".join(f"{r} {COMP[r].value}" for r in consumers) or "-"
        caps = sorted({d.value for n in c.conns.values() if n != GND for d, _ in members(n)
                       if d.part.kind == "cap"})
        rows.append([c.ref, esc(c.part.mpn), esc(c.value), esc(c.part.package), cons,
                     esc(", ".join(caps) or "-"), esc(c.note or c.part.description)])
    clk = USE_BY_NET.get("RMII_REF_CLK")
    L += ["### 1.4 Clocks", "",
          md_table(["Ref", "MPN", "Value", "Package", "Consumer", "Load caps", "Notes"], rows), ""]
    if clk:
        L += [f"RMII reference: GPIO{clk.gpio} {code(clk.net)} -- {esc(clk.function)}. {esc(clk.notes)}.", ""]
    return L


def _gpio_notes(u: bs.GpioUse) -> str:
    notes = []
    if u.gpio in p4.STRAPPING_GPIOS:
        notes.append("**STRAP**")
    if u.notes:
        notes.append(esc(u.notes))
    if u.gpio in p4.RESET_STATE:
        notes.append(f"Reset: {esc(p4.RESET_STATE[u.gpio])}")
    if u.mux == "IO_MUX":
        sig = iomux_signal(u)
        if sig:
            notes.append(f"IO_MUX {sig} legal on GPIO {'/'.join(map(str, p4.IOMUX_OPTIONS[sig]))}")
        else:
            notes.append("IO_MUX signal not listed in `IOMUX_OPTIONS` (verify)")
    ev = evidence(u.net)
    if ev:
        notes.append("Netlist: " + esc(", ".join(ev)))
    return "; ".join(notes)


def _domain_cell(g: int) -> str:
    parts = []
    for d in p4.gpio_domain(g).split("/"):
        pad = PAD_BY_NAME.get(d)
        parts.append(f"{d} = {code(u1_net(pad) or '?')}")
    return " / ".join(parts)


MUX_LABEL = {"IO_MUX": "IO_MUX fixed", "GPIO matrix": "GPIO matrix", "GPIO": "GPIO", "Strap": "Strap"}


def _gpio_table() -> list[str]:
    rows = []
    for g in range(55):
        pad = p4.GPIO_PAD[g]
        if g in USE:
            u = USE[g]
            rows.append([f"GPIO{g}", pad, _domain_cell(g), code(u.net), esc(u.function), esc(u.block),
                         MUX_LABEL.get(u.mux, esc(u.mux)), _gpio_notes(u)])
        elif g in bs.GPIO_NC:
            fixed = [s for s, o in p4.IOMUX_OPTIONS.items() if g in o]
            notes = [esc(bs.GPIO_NC[g])]
            if g in p4.STRAPPING_GPIOS:
                notes.insert(0, "**STRAP**")
            if fixed:
                notes.append("IO_MUX functions on this pad: " + ", ".join(fixed))
            rows.append([f"GPIO{g}", pad, _domain_cell(g), "-", "Not connected", "-", "NC", "; ".join(notes)])
        else:
            rows.append([f"GPIO{g}", pad, _domain_cell(g), "-", "**UNDECIDED**", "-", "-", "-"])
    return [md_table(["GPIO", "Pad #", "Power domain", "Net", "Function", "Block", "Mux", "Notes"], rows,
                     "lrllllll")]


def _dedicated_tables() -> list[str]:
    sig_rows, pwr_rows = [], []
    for pad in sorted(bs.DEDICATED_NETS, key=int):
        name, net = p4.PAD_NAME[pad], bs.DEDICATED_NETS[pad]
        if name.startswith("VDD") or name == "GND":
            caps = [c for c in bs.COMPONENTS if isinstance(c.place, bs.Near) and c.place.ref == "U1"
                    and c.place.pad == pad and c.part.kind == "cap"]
            feeds = [c for c in bs.COMPONENTS if isinstance(c.place, bs.Near) and c.place.ref == "U1"
                     and c.place.pad == pad and c.part.kind == "res" and net in c.conns.values()]
            dec = " + ".join(c.value for c in caps)
            dec = f"{dec} ({refs_join(c.ref for c in caps)})" if caps else "-"
            fd = ", ".join(f"{c.ref} {c.value} from {code(other_end(c, next(p for p, n in c.conns.items() if n == net)))}"
                           for c in feeds) or "-"
            pwr_rows.append([pad, esc(name), p4.PAD_TYPE[pad], code(net), dec, fd])
        else:
            grp = DEDICATED_GROUP.get(pad, "Reset / power-up" if name == "CHIP_PU" else "-")
            sig_rows.append([pad, esc(name), esc(grp), code(net), "; ".join(describe(net)) or "-"])
    return ["### 2.2 Dedicated (non-GPIO) signal pads", "",
            md_table(["Pad #", "Pad name", "Function group", "Net", "Board connection (netlist)"], sig_rows,
                     "rllll"), "",
            "### 2.3 Power / ground pads", "",
            md_table(["Pad #", "Pad name", "Type", "Net", "Decoupling at the pad (<= 2 mm)", "Feed"],
                     pwr_rows, "rlllll"), ""]


def _conflicts() -> list[str]:
    L = ["## 3. Conflict analysis", ""]
    sets = interface_sets()
    all_gpio_pads = set(p4.GPIO_PAD.values())
    rows = []
    for label, kind, g, pads in sets:
        rows.append([esc(label), kind, ranges(g) if g else "-", ranges(pads),
                     "yes" if pads <= all_gpio_pads else ("no" if not pads & all_gpio_pads else "**mixed**")])
    L += ["### 3.1 Resource sets", "",
          md_table(["Interface", "Kind", "GPIOs", "U1 pads", "Pads are GPIO pads?"], rows), ""]
    # matrix
    hdr = ["", *[esc(s[0]) for s in sets]]
    rows, lines, total = [], [], 0
    for i, (la, _, _, pa) in enumerate(sets):
        r = [f"**{esc(la)}**"]
        for j, (lb, _, _, pb) in enumerate(sets):
            if i == j:
                r.append(f"({len(pa)})")
                continue
            inter = pa & pb
            total += len(inter) if j > i else 0
            r.append("0" if not inter else f"**{ranges(inter)}**")
            if j > i:
                lines.append(f"{la:<16} & {lb:<16} = {sorted(inter, key=int) if inter else 'set()'}")
        rows.append(r)
    ded_vs_gpio = set().union(*(s[3] for s in sets if s[1] == "dedicated")) & all_gpio_pads
    L += ["### 3.2 Pairwise overlap (U1 pad numbers; diagonal = set size)", "",
          md_table(hdr, rows, "l" + "c" * len(sets)), "",
          "Intersections computed by `tools/gen_docs.py` at generation time:", "", "```text", *lines,
          f"dedicated MIPI/USB-HS pads & GPIO pads = {sorted(ded_vs_gpio, key=int) if ded_vs_gpio else 'set()'}",
          f"GPIO_MAP duplicates                    = "
          f"{sorted(g for g, n in Counter(u.gpio for u in bs.GPIO_MAP).items() if n > 1) or 'set()'}",
          "```", "",
          f"Result: **{total} overlapping pads** across {len(sets) * (len(sets) - 1) // 2} interface pairs. "
          "MIPI DSI/CSI and USB 2.0 HS live on dedicated D-PHY / UTMI pads that are not GPIOs, so they "
          "cannot collide with any GPIO-matrix or IO_MUX assignment.", ""]

    # IO_MUX legality
    rows = []
    for u in sorted(bs.GPIO_MAP, key=lambda u: u.gpio):
        if u.mux != "IO_MUX":
            continue
        sig = iomux_signal(u)
        opts = p4.IOMUX_OPTIONS.get(sig, ()) if sig else ()
        rows.append([sig or "-", code(u.net), f"GPIO{u.gpio}", "/".join(map(str, opts)) or "-",
                     status(u.gpio in opts) if sig else "not in `IOMUX_OPTIONS`"])
    L += ["### 3.3 IO_MUX-fixed signals: chosen pad vs legal pads", "",
          md_table(["Signal", "Net", "Chosen", "Legal (IOMUX_OPTIONS)", "Status"], rows), ""]

    # avoided alternatives
    chosen = {iomux_signal(u): u.gpio for u in bs.GPIO_MAP if iomux_signal(u)}
    fixed_on = defaultdict(list)
    for s, o in p4.IOMUX_OPTIONS.items():
        if len(o) == 1:
            fixed_on[o[0]].append(s)
    rows = []
    for sig, opts in p4.IOMUX_OPTIONS.items():
        if len(opts) < 2:
            continue
        ch = chosen.get(sig)
        for g in opts:
            if g == ch:
                continue
            u = USE.get(g)
            occ = f"{code(u.net)} ({esc(u.block)})" if u else ("NC" if g in bs.GPIO_NC else "-")
            reasons = []
            if u and u.block not in ("Header",) and "Ethernet" not in u.block:
                reasons.append(f"collides with {esc(u.block)} {code(u.net)}")
            fx = [s for s in fixed_on.get(g, []) if s != sig]
            if fx:
                reasons.append("pad owns fixed " + "/".join(fx))
            if p4.gpio_domain(g) == "VDD_IO_5" and g in bs.GPIO_NC:
                reasons.append(f"{p4.gpio_domain(g)} = {code(u1_net(PAD_BY_NAME['VDD_IO_5']))} (0 V at boot)")
            if g in p4.STRAPPING_GPIOS:
                reasons.append("strapping pin")
            if u and "Ethernet" in u.block:
                reasons.append(f"taken by Ethernet {code(u.net)}")
            if not reasons:
                reasons.append("free alternative, not needed" + (" (header pin)" if u and u.block == "Header" else ""))
            rows.append([sig, f"GPIO{ch}" if ch is not None else "not used", f"GPIO{g}", occ,
                         ", ".join(fx) or "-", "; ".join(reasons)])
    L += ["### 3.4 Alternative IO_MUX pads deliberately avoided", "",
          "Every multi-option IO_MUX signal in `IOMUX_OPTIONS`; each row is a legal pad the design did "
          "*not* use and what already occupies it.", "",
          md_table(["Signal", "Chosen", "Alternative", "Occupant in this design", "Fixed IO_MUX on that pad",
                    "Why avoided"], rows), ""]
    # forced choices
    sd_pads = {g for s, o in p4.IOMUX_OPTIONS.items() if s.startswith("SD0_") for g in o}
    forced = []
    for sig in (s for s in p4.IOMUX_OPTIONS if s.startswith("RMII_") and s in chosen):
        clean = [g for g in p4.IOMUX_OPTIONS[sig] if g not in sd_pads and g not in bs.GPIO_NC]
        strap = [g for g in clean if g in p4.STRAPPING_GPIOS]
        forced.append([sig, "/".join(map(str, p4.IOMUX_OPTIONS[sig])), "/".join(map(str, clean)) or "none",
                       f"GPIO{chosen.get(sig)}" if sig in chosen else "-",
                       "only non-SDIO option is a strapping pin" if clean and clean == strap else "-"])
    L += ["Legal RMII pads that do not collide with SDMMC slot 0 (GPIO "
          f"{ranges(sd_pads)}) or the NC VDD_IO_5 pads:", "",
          md_table(["Signal", "All legal", "SDIO-free", "Chosen", "Consequence"], forced), "",
          "TXD0/TXD1 have no SDIO-free option except the strapping pins GPIO34/GPIO35, which is why "
          "GPIO35 carries both RMII_TXD1 and the BOOT strap (see section 4).", ""]
    return L


def _strapping() -> list[str]:
    L = ["## 4. Strapping and boot", ""]
    rows = []
    for g in sorted(p4.STRAPPING_GPIOS):
        u = USE.get(g)
        net = u.net if u else None
        ev = evidence(net) if net else []
        ics = [f"{c.ref}.{esc(pin_name(c, pad))}" for n in ([net] if net else [])
               for c, pad in members(n) if c.part.kind == "ic" and c.ref != "U1"]
        ics += [f"{c2.ref}.{esc(pin_name(c2, p2))} via {c.ref}" for c, pad in members(net or "")
                if is_series(c, 100.0) and other_end(c, pad) not in RAILS
                for c2, p2 in members(other_end(c, pad)) if c2.part.kind == "ic" and c2.ref != "U1"]
        pulls = [e for e in ev if re.search(r" to (\+3V3|VDD\S*)$", e)]
        downs = [e for e in ev if e.endswith(f"to {GND}") and not e.startswith("SW")]
        rs = p4.RESET_STATE.get(g, "-")
        if pulls:
            level = f"1 (external pull-up {pulls[0].split()[0]})"
        elif downs:
            level = f"0 ({downs[0].split()[0]})"
        elif "WPU" in rs:
            level = "1 (internal WPU)"
        else:
            level = "undefined: no board pull" + (f" (only {', '.join(ics)} on the net)" if ics else "")
        rows.append([f"GPIO{g}", code(net or "-"), esc(rs), esc(", ".join(ev + ics) or "-"), level,
                     esc(u.notes if u else "-")])
    L += [md_table(["GPIO", "Net", "Reset state", "Netlist (pulls / switches)", "Level at reset",
                    "Spec note"], rows), ""]
    b, q = p4.BOOT_MODE_GPIO, p4.DOWNLOAD_QUALIFIER_GPIO
    bnet, qnet = USE[b].net, USE[q].net
    bev, qev = evidence(bnet), evidence(qnet)
    pull_b = next((e.split()[0] for e in bev if "to +3V3" in e), "?")
    pull_q = next((e.split()[0] for e in qev if "to +3V3" in e), "?")
    lows = [e.split()[0].split(".")[0] for e in bev if e.startswith(("SW", "Q"))]
    L += [md_table([f"GPIO{b}", f"GPIO{q}", "Boot mode", "How the board gets there"], [
        ["1", "x", "SPI boot (normal)", f"{pull_b} pull-up holds GPIO{b} high"],
        ["0", "1", "Joint download boot (UART0 / USB)",
         f"{' or '.join(lows) or '?'} pulls GPIO{b} low while CHIP_PU rises; {pull_q} keeps GPIO{q} = 1"],
        ["0", "0", "not a listed boot mode", f"prevented: nothing in the netlist pulls GPIO{q} low"],
    ], "ccll"), ""]
    pad = p4.GPIO_PAD[b]
    stubs = []
    for c, _ in members(bnet):
        if c.ref == "U1" or c.part.kind in ("res", "cap"):
            continue
        pos = board_xy(c)
        if pos is None:
            an = near_anchor(c)
            if an:
                stubs.append(f"{c.ref} ~{f(dist(u1_pad_xy(pad), an[0]), 0)} mm (near {an[2]}, +/-{f(an[1], 0)} mm)")
        else:
            stubs.append(f"{c.ref} {f(dist(u1_pad_xy(pad), pos), 0)} mm")
    L += [f"Review flag (computed): GPIO{b} is also {code(bnet)} (50 MHz RMII TX). Straight-line distance "
          f"from U1 pad {pad} to each active device on that net: {esc('; '.join(stubs))}. The BOOT button and "
          "auto-program transistor therefore add a long stub on the SoC side of the series resistor; keep "
          "the stub short or isolate it with a series resistor (~1k) at the tap -- with the "
          f"{pull_b} 10k pull-up a 1k series still gives a valid low (~0.3 V).", ""]
    undefined = [r[0] for r in rows if r[4].startswith("undefined")]
    if undefined:
        L += [f"Strapping pins with no defined level at reset: {', '.join(undefined)}. Acceptable only "
              "where the spec note says the strap value is ignored ('any value' / eFuse-gated); otherwise "
              "add a pull.", ""]
    return L


def _power_domains() -> list[str]:
    tree = power_tree()
    parent = {r["net"]: r for r in tree}
    volt = rail_voltage(tree)
    doms: dict[str, list[int]] = defaultdict(list)
    for g in range(55):
        doms[p4.gpio_domain(g)].append(g)
    rows = []
    for dom, gs in doms.items():
        supplies = []
        for d in dom.split("/"):
            pad = PAD_BY_NAME.get(d)
            net = u1_net(pad) if pad else None
            short, how = volt.get(net, ("-", ""))
            src = parent.get(net)
            via = ", ".join(v["label"] for _, v in src["feeds"]) if src else "-"
            supplies.append(f"{d} (pad {pad}) = {code(net)}, {esc(short)} via {esc(via)}")
        used = [g for g in gs if g in USE]
        nc = [g for g in gs if g in bs.GPIO_NC]
        rows.append([esc(dom), "<br>".join(supplies), ranges(gs), ranges(used) or "-", ranges(nc) or "-"])
    L = ["## 5. Power domains", "", md_table(["Domain", "Supply pad = net", "GPIOs", "Used", "NC"], rows), ""]
    sd_pwr = next((u for u in bs.GPIO_MAP if u.block == "microSD" and "PWR" in u.net), None)
    vio5 = u1_net(PAD_BY_NAME["VDD_IO_5"])
    nc_dom = sorted({p4.gpio_domain(g) for g in bs.GPIO_NC})
    notes = [f"GPIO{ranges(bs.GPIO_NC)} are NC: domain {', '.join(nc_dom)} is {code(vio5)}, the on-chip "
             f"LDO output that is 0 V at boot and 1.8 V in UHS-I mode ({esc(next(iter(bs.GPIO_NC.values())))})."]
    sd_io = [u for u in bs.GPIO_MAP if u.block == "microSD" and u.mux == "IO_MUX"]
    sd_pulls = sorted({e.split()[0] for u in sd_io for e in evidence(u.net) if e.split(" via ")[0].endswith(vio5)},
                      key=natural_key)
    notes.append(f"The SDIO pads GPIO{ranges(u.gpio for u in sd_io)} share that domain, so the card bus is dead "
                 f"until firmware enables the LDO; the card pull-ups {ref_ranges(sd_pulls)} go to the same "
                 f"{code(vio5)} rail.")
    if sd_pwr:
        pad = PAD_BY_NAME[p4.gpio_domain(sd_pwr.gpio).split('/')[0]]
        notes.append(f"The card power switch GPIO{sd_pwr.gpio} {code(sd_pwr.net)} is in "
                     f"{p4.gpio_domain(sd_pwr.gpio)} = {code(u1_net(pad))}: a 3.3 V high fully turns off the "
                     f"P-FET ({esc(sd_pwr.notes)}); netlist: {esc(', '.join(evidence(sd_pwr.net)))}.")
    L += [f"* {n}" for n in notes] + [""]
    return L


def _routing() -> list[str]:
    L = ["## 6. Routing rules", ""]
    links = {l["label"]: l for l in hs_links()}
    rows = []
    usb, mipi, se, eth = rule("USB_90"), rule("MIPI_100"), rule("SE_50"), rule("ETH_100")

    def zrow(name, r, tol, guide):
        if not r:
            return [name, guide, "rule missing", "**FAIL**"]
        err = abs(r.achieved_ohm - r.target_ohm) / r.target_ohm
        geo = (f"{code(r.netclass)} w {f(r.width_mm, 3)} mm" + (f" / s {f(r.gap_mm, 3)} mm" if r.gap_mm else "")
               + f" -> {f(r.achieved_ohm, 1)} ohm ({err * 100:.1f} % off)")
        return [name, guide, geo, status(err <= tol)]

    rows.append(zrow("USB 2.0 HS / FS", usb, USB_Z_TOL, f"90 ohm differential +/-{USB_Z_TOL:.0%}"))
    rows.append(zrow("MIPI D-PHY (DSI, CSI)", mipi, MIPI_Z_TOL, f"100 ohm differential +/-{MIPI_Z_TOL:.0%}"))
    rows.append(["MIPI skew", f"intra-pair <= {MIPI_INTRA_MIL} mil ({f(MIPI_INTRA_MIL * MIL_MM, 3)} mm), "
                 f"inter-pair <= {MIPI_INTER_MIL} mil ({f(MIPI_INTER_MIL * MIL_MM, 3)} mm)",
                 "KiCad length-tuning rule on the `MIPI_100` class", "layout rule"])
    rows.append(zrow("SDIO", se, SE_Z_TOL, "50 ohm single-ended"))
    sd = links.get("SDIO (SDMMC slot 0)")
    if sd:
        eu = dist(sd["a"], sd["b"])
        mh = abs(sd["a"][0] - sd["b"][0]) + abs(sd["a"][1] - sd["b"][1])
        rows.append(["SDIO length", f"CMD/DATA within +/-{SDIO_SKEW_MIL} mil of CLK; total <= "
                     f"{SDIO_TOTAL_MIL} mil ({f(SDIO_TOTAL_MIL * MIL_MM, 1)} mm)",
                     f"U1 -> {sd['to']}: {f(eu, 1)} mm straight / {f(mh, 1)} mm Manhattan "
                     f"({f(mh / MIL_MM, 0)} mil)", status(mh / MIL_MM <= SDIO_TOTAL_MIL)])
    y = soc_crystal()
    if y and board_xy(y):
        d = min(dist(board_xy(y), u1_pad_xy(p)) for p in ("99", "100"))
        ser = [c.ref for p in ("99", "100") for c, _ in members(u1_net(p)) if c.part.kind == "res"]
        rows.append([f"SoC crystal ({esc(y.value)})", f">= {f(XTAL_MIN_MM, 1)} mm from the clock pads; no vias on the "
                     "XTAL traces; 0R at the chip",
                     f"{y.ref} centre {f(d, 2)} mm from pad 99/100; series {', '.join(ser)}",
                     status(d >= XTAL_MIN_MM)])
    en = u1_net("79")
    dcdc = next((c for c, _ in members(en or "") if c.part.kind == "ic" and c.ref != "U1"), None)
    if dcdc and board_xy(dcdc):
        d = min(dist(board_xy(dcdc), u1_pad_xy(p)) for p in ("78", "79"))
        ind = [c for c in bs.COMPONENTS if c.part.kind == "ind" and net_of(dcdc, "SW") in c.conns.values()]
        rows.append(["VDD_HP DCDC", "external buck close to the chip; short SW loop",
                     f"{dcdc.ref} {dcdc.value} {f(d, 1)} mm from FB/EN pads 78/79 "
                     f"({f(keepout_clearance(board_xy(dcdc)), 1)} mm outside the keep-out); "
                     f"{', '.join(i.ref for i in ind) or '?'} adjacent", "OK (as close as the keep-out allows)"])
    ref = USE_BY_NET.get("RMII_REF_CLK")
    if ref:
        ser = [c for c, pad in members(ref.net) if is_series(c, 100.0)]
        rows.append(["RMII 50 MHz clock", "series resistor at the clock driver",
                     ", ".join(f"{c.ref} {c.value} ohm ({esc(c.note)})" for c in ser) or "none",
                     status(bool(ser))])
    rmii = [u for u in bs.GPIO_MAP if u.net.startswith("RMII_") and u.net != "RMII_REF_CLK"]
    ser = []
    for u in rmii:
        for c, pad in members(u.net):
            if is_series(c, 100.0) and other_end(c, pad) not in RAILS:
                ser.append(f"{c.ref} {c.value}")
    rows.append(["RMII data", "source termination at the driver", ", ".join(ser), status(len(ser) >= len(rmii))])
    rows.append(zrow("Ethernet MDI", eth, SE_Z_TOL, "100 ohm differential (PHY vendor)"))
    fl = [c.ref for p in ("27", "28", "29", "31", "32", "33") for c, _ in members(u1_net(p) or "")
          if c.part.kind == "res"]
    rows.append(["QSPI flash", "50 ohm SE, reserve series R at the SoC", f"{len(fl)} x 0R: {ref_ranges(fl)}",
                 status(len(fl) == 6)])
    l2 = next((l for l in imp.STACKUP if l.name == "In1.Cu"), None)
    rows.append(["Reference plane", "HS pairs over an unbroken ground plane",
                 f"L1 routing over In1.Cu: {esc(l2.function) if l2 else '?'}", "layout rule"])
    L += ["### 6.1 Espressif ESP32-P4 layout guideline vs this board", "",
          md_table(["Interface", "Guideline", "This board (computed)", "Status"], rows), ""]
    L += ["### 6.2 Controlled-impedance geometry (`impedance_rules()`, surface microstrip over L2)", "",
          impedance_table(), "",
          "Closed-form Hammerstad-Jensen / IPC-2141A starting geometry; PCBWay confirms with a field "
          "solver and trims widths by +/-10 um.", "",
          "### 6.3 Stack-up (`STACKUP`)", "", stackup_table(), ""]
    # net classes + diff pairs
    cls = defaultdict(list)
    for n in NETS:
        cls[bs.netclass_of(n)].append(n)
    rows = [[code(c), str(len(ns)), esc(", ".join(sorted(ns, key=natural_key)))]
            for c, ns in sorted(cls.items()) if c != "Default"]
    rows.append([code("Default"), str(len(cls["Default"])), "all other nets"])
    L += ["### 6.4 Net classes (`netclass_of()`)", "", md_table(["Class", "Nets", "Members"], rows, "lrl"), ""]
    rows = []
    for p, n, c in bs.DIFF_PAIRS:
        ok = p in NETS and n in NETS and bs.netclass_of(p) == bs.netclass_of(n) == c
        rows.append([code(p), code(n), code(c), str(len(NETS.get(p, []))), str(len(NETS.get(n, []))), status(ok)])
    L += ["### 6.5 Differential pairs (`DIFF_PAIRS`)", "",
          md_table(["P", "N", "Class", "P pins", "N pins", "Status"], rows, "lllrrl"), ""]
    return L


def render_task1() -> str:
    problems = bs.validate()
    L = [BANNER, "", "# TASK 1: Architecture & GPIO pinout mapping", "",
         f"Source of truth: `hardware/lib/board_spec.py`, `esp32p4_pinout.py`, `impedance.py`. "
         f"`validate()`: **{'clean' if not problems else f'{len(problems)} problem(s)'}**.", ""]
    if problems:
        L += ["```text", *problems, "```", ""]
    L += _architecture()
    used = len(USE)
    L += ["## 2. Pinout", "", "### 2.1 GPIO0-GPIO54", "",
          f"{used} GPIOs used, {len(bs.GPIO_NC)} NC, {55 - used - len(bs.GPIO_NC)} undecided. "
          "Mux: *IO_MUX fixed* = the peripheral only works on this pad; *GPIO matrix* = routed through "
          "the GPIO matrix (any pad); *GPIO* = plain software GPIO; *Strap* = strap-only. "
          "\"Netlist\" in Notes is extracted from the component list (pulls, switches, transistors, "
          "following one series resistor).", ""]
    L += _gpio_table() + [""]
    L += _dedicated_tables()
    L += _conflicts()
    L += _strapping()
    L += _power_domains()
    L += _routing()
    flags = verification_flags()
    if flags:
        L += ["## 7. Items pending verification (from spec strings)", "",
              md_table(["Where", "Field", "Text"], [[esc(a), b, esc(c)] for a, b, c in flags]), ""]
    return "\n".join(L).rstrip() + "\n"


# ===========================================================================
# TASK 4 -- BOM
# ===========================================================================

BOM_HEADERS = ["Item #", "Designator", "Quantity", "Value/Name", "Package/Footprint",
               "Manufacturer Part Number (MPN)", "Manufacturer", "Description", "Mount (SMD/THT)",
               "LCSC #", "Assembly note"]
BOM_ALIGN = "rlrllllllll"


def _bom_note(line: dict) -> str:
    part = line["part"]
    notes = []
    if line["dnp"]:
        notes.append("DO NOT POPULATE")
        comp_notes = sorted({COMP[r].note for r in line["refs"] if COMP[r].note})
        notes += comp_notes
    else:
        if part.tht:
            notes.append("THT, top side")
        elif re.search(r"\bTHT\b", part.description):
            notes.append("SMD with THT legs (paste-in-hole / hand-solder the legs)")
        if part is U1.part:
            notes.append("EPAD on the capped via-in-pad array")
        m = re.search(r"([\d.]+) mm pitch", part.package)
        if m and float(m.group(1)) <= 0.4:
            notes.append(f"fine pitch {m.group(1)} mm")
        if re.search(r"PENDING|UNVERIFIED", part.pin_source + part.description, re.I):
            notes.append("PENDING verification: " + part.pin_source)
        if not part.lcsc:
            notes.append("no LCSC number")
    return "; ".join(notes)


def bom_rows() -> list[tuple[bool, list[str]]]:
    lines = bs.bom_lines()
    ordered = [l for l in lines if not l["dnp"]] + [l for l in lines if l["dnp"]]
    rows = []
    for item, line in enumerate(ordered, 1):
        part = line["part"]
        refs = sorted(line["refs"], key=natural_key)
        fp = part.footprint.split(":")[-1]
        rows.append((bool(line["dnp"]), [
            str(item), ", ".join(refs), str(line["qty"]), str(line["value"]), f"{part.package} [{fp}]",
            part.mpn, part.manufacturer, part.description, "THT" if part.tht else "SMD", part.lcsc,
            _bom_note(line)]))
    return rows


def render_bom_csv() -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(BOM_HEADERS)
    for _, r in bom_rows():
        w.writerow(r)
    return buf.getvalue()


def bom_summary() -> dict:
    rows = bom_rows()
    fit = [r for d, r in rows if not d]
    dnp = [r for d, r in rows if d]
    comps = [c for c in bs.COMPONENTS if c.part.kind != "mech" and not c.dnp]
    smd = [c for c in comps if not c.part.tht]
    tht = [c for c in comps if c.part.tht]
    sides = {c.place.side for c in bs.COMPONENTS if c.place is not None}
    return {
        "lines": len(fit), "placements": sum(int(r[2]) for r in fit), "comps": len(comps),
        "smd_lines": sum(1 for r in fit if r[8] == "SMD"), "tht_lines": sum(1 for r in fit if r[8] == "THT"),
        "smd": len(smd), "tht": len(tht), "tht_refs": [c.ref for c in tht],
        "dnp_lines": len(dnp), "dnp_refs": [c.ref for c in bs.COMPONENTS if c.dnp and c.part.kind != "mech"],
        "mech": [c.ref for c in bs.COMPONENTS if c.part.kind == "mech"], "sides": sides,
        "no_lcsc": [r[1] for r in fit if not r[9]],
        "legs": [c.ref for c in smd if re.search(r"\bTHT\b", c.part.description)],
    }


def render_task4() -> str:
    rows = bom_rows()
    s = bom_summary()
    bottom = bs.bottom_side_refs()
    side = ("single-sided top (F.Cu) assembly" if s["sides"] == {"F"} else
            f"double-sided assembly: {s['placements'] - len(bottom)} top + {len(bottom)} bottom "
            f"(0402 decoupling under U1: {', '.join(bottom)})")

    def cells(r):
        return [esc(c) for c in r]

    L = [BANNER, "", "# TASK 4: BOM for PCBWay turnkey assembly", "",
         f"Generated from `board_spec.bom_lines()`; the CSV `hardware/output/bom_pcbway.csv` holds exactly "
         f"the rows of the two tables below (same columns, same order).", "",
         f"**Summary:** {s['lines']} unique fitted line items, {s['placements']} placements "
         f"({s['smd']} SMD on {s['smd_lines']} lines, {s['tht']} THT on {s['tht_lines']} lines: "
         f"{refs_join(s['tht_refs'])}), {side}. "
         + (f"SMD parts with THT shell/retention legs: {refs_join(s['legs'])}. " if s["legs"] else "") +
         f"DNP: {len(s['dnp_refs'])} footprints on {s['dnp_lines']} lines ({refs_join(s['dnp_refs'])}). "
         f"Excluded (mechanical, no part to buy): {refs_join(s['mech'])}. "
         f"Check: BOM placements {s['placements']} == fitted non-mechanical components {s['comps']} -> "
         f"{status(s['placements'] == s['comps'])}.", "",
         "## 1. Fitted parts", "",
         md_table(BOM_HEADERS, [cells(r) for d, r in rows if not d], BOM_ALIGN), "",
         "## 2. Do Not Populate", "",
         "Footprints exist on the PCB (and in the pick-and-place file); do not buy or place these.", "",
         md_table(BOM_HEADERS, [cells(r) for d, r in rows if d], BOM_ALIGN), ""]
    if s["no_lcsc"]:
        L += [f"Lines without an LCSC number (PCBWay sources by MPN): {esc('; '.join(s['no_lcsc']))}.", ""]
    flags = verification_flags()
    if flags:
        L += ["## 3. Verification flags carried from the spec", "",
              md_table(["Where", "Field", "Text"], [[esc(a), b, esc(c)] for a, b, c in flags]), ""]
    L += _pcbway_notes(s)
    return "\n".join(L).rstrip() + "\n"


def _pcbway_notes(s: dict) -> list[str]:
    cu = [l for l in imp.STACKUP if l.kind == "copper"]
    diel = [l for l in imp.STACKUP if l.kind == "dielectric"]
    x0, y0, x1, y1 = bs.BOARD_OUTLINE
    tv = bs.THERMAL_VIA
    zr = "; ".join(f"{r.netclass} {f(r.target_ohm, 0)} ohm {'diff' if r.kind == 'diff' else 'SE'} "
                   f"(w {f(r.width_mm, 3)}" + (f" / s {f(r.gap_mm, 3)}" if r.gap_mm else "") + " mm, L1 ref L2)"
                   for r in imp.impedance_rules())
    rows = [
        ["Layers / build", f"{len(cu)}-layer HDI 1+2+1: laser microvias L1->L2 and L4->L3, mechanical "
                           "through-vias L1->L4"],
        ["Finished thickness", f"{f(imp.BOARD_THICKNESS_MM, 2)} mm (sum of `STACKUP`)"],
        ["Board size", f"{f(x1 - x0, 0)} x {f(y1 - y0, 0)} mm, corner radius {f(bs.BOARD_CORNER_R, 1)} mm"],
        ["Materials", esc("; ".join(sorted({l.material for l in diel})))],
        ["Copper", esc("; ".join(f"{l.name} {l.material}" for l in cu))],
        ["Surface finish", "ENIG (flat pads for the 0.35 mm-pitch QFN-104 and the capped via-in-pad EPAD)"],
        ["Impedance control", esc(zr) + "; tolerance +/-10 %, fab to confirm with its field solver"],
        ["Via-in-pad", f"{tv['grid']}x{tv['grid']} array, {f(tv['drill_mm'], 2)} mm drill / "
                       f"{f(tv['pad_mm'], 2)} mm pad, {f(tv['pitch_mm'], 1)} mm pitch in the U1 EPAD: "
                       f"{esc(tv['fill'])}, planarised flush"],
        ["Min track / space", "3.5 / 3.5 mil (0.089 mm)"],
        ["Microvia", "0.1 mm laser-drilled (L1-L2, L4-L3), in the 1080 prepreg"],
        ["Hole plating", f">= {f(PLATING_UM, 0)} um average (assumed by the thermal-via calculation in TASK 2)"],
        ["Assembly", f"{side_text(s)}; {s['smd']} SMD + {s['tht']} THT placements; finest pitch 0.35 mm (U1); "
                     f"fiducials {', '.join(f'{k} {xy(v)}' for k, v in bs.FIDUCIALS.items())}"],
        ["DNP", refs_join(s["dnp_refs"])],
    ]
    return ["## 4. PCBWay ordering notes", "", md_table(["Item", "Requirement"], rows), "",
            "Stack-up to attach to the order:", "", stackup_table(), ""]


def side_text(s: dict) -> str:
    bottom = bs.bottom_side_refs()
    return ("single-sided, top side only" if s["sides"] == {"F"} else
            f"double-sided: {len(bottom)} x 0402 on the bottom ({', '.join(bottom)}), "
            f"all other parts on top; one extra stencil + reflow pass")


# ===========================================================================
# TASK 2 -- mechanical & thermal
# ===========================================================================

def thermal_model() -> dict:
    tv = bs.THERMAL_VIA
    d, t, L = tv["drill_mm"], PLATING_UM / 1000.0, imp.BOARD_THICKNESS_MM
    n = tv["grid"] ** 2
    a_ring = math.pi / 4 * (d ** 2 - (d - 2 * t) ** 2)                     # mm^2
    r_via = (L * 1e-3) / (K_CU * a_ring * 1e-6)
    r_arr = r_via / n
    a_full = math.pi / 4 * d ** 2
    r_arr_cu = (L * 1e-3) / (K_CU * a_full * 1e-6) / n
    l12 = 0.0
    for layer in imp.STACKUP:
        if layer.name == "In1.Cu":
            break
        l12 += layer.thickness_mm
    r_l12 = r_arr * l12 / L
    body = p4.BODY_MM[0] * p4.BODY_MM[1]
    tim_mm = float(re.search(r"([\d.]+)\s*mm", bs.HEATSINK["tim"]).group(1))
    r_tim = (tim_mm * 1e-3) / (K_TIM * body * 1e-6)
    epad = p4.EPAD_SIZE_MM ** 2
    r_solder = (SOLDER_UM * 1e-6) / (K_SOLDER * epad * PASTE_COVERAGE * 1e-6)
    bx, by = bs.HEATSINK["base_mm"]
    fin_h = bs.HEATSINK["height_mm"] - BASE_T_MM
    a_hs = bx * by + PIN_GRID ** 2 * 4 * PIN_SIDE_MM * fin_h                  # mm^2
    th_nat = 1 / (H_NAT * FIN_EFF_NAT * a_hs * 1e-6)
    th_fan = 1 / (H_FAN * FIN_EFF_FAN * a_hs * 1e-6)
    x0, y0, x1, y1 = bs.BOARD_OUTLINE
    a_board = 2 * (x1 - x0) * (y1 - y0) * 1e-6
    r_bd_nat = 1 / (H_NAT * a_board * BOARD_SPREAD_EFF)
    r_bd_fan = 1 / ((H_NAT + H_BOARD_EXHAUST) / 2 * a_board * BOARD_SPREAD_EFF)
    r_bot_common = THETA_JC_BOT + r_solder + r_arr
    r_gap = (GAP_PAD_MM * 1e-3) / (K_GAP_PAD * WINDOW_MM ** 2 * 1e-6)
    r_top_bare = THETA_JC_TOP + 1 / (H_NAT * body * 1e-6)
    scen = []
    for name, r_top, r_bot in (
            ("Heatsink + fan (normal)", THETA_JC_TOP + r_tim + th_fan, r_bot_common + r_bd_fan),
            ("Heatsink, fan stopped / zero-RPM", THETA_JC_TOP + r_tim + th_nat, r_bot_common + r_bd_nat),
            ("No heatsink, natural convection", r_top_bare, r_bot_common + r_bd_nat)):
        r_ja = 1 / (1 / r_top + 1 / r_bot)
        scen.append({"name": name, "r_top": r_top, "r_bot": r_bot, "r_ja": r_ja,
                     "share_bot": r_top / (r_top + r_bot)})
    p_lo = sum(x[1] for x in POWER_ESTIMATE)
    p_hi = sum(x[2] for x in POWER_ESTIMATE)
    return {"d": d, "t": t, "L": L, "n": n, "a_ring": a_ring, "r_via": r_via, "r_arr": r_arr,
            "r_arr_cu": r_arr_cu, "l12": l12, "r_l12": r_l12, "tim_mm": tim_mm, "r_tim": r_tim,
            "r_solder": r_solder, "a_hs": a_hs, "th_nat": th_nat, "th_fan": th_fan, "fin_h": fin_h,
            "a_board": a_board, "r_bd_nat": r_bd_nat, "r_bd_fan": r_bd_fan, "r_gap": r_gap,
            "scen": scen, "p_lo": p_lo, "p_hi": p_hi, "body": body}


def _power_ceiling() -> tuple[float | None, str]:
    tree = power_tree()
    row = next((r for r in tree if r["feeds"] and r["feeds"][0][1]["kind"] == "buck"
                and any(u1_net(p) == r["net"] for p in U1.conns if p4.PAD_NAME[p].startswith("VDD_HP"))), None)
    if not row:
        return None, ""
    ic = row["feeds"][0][1]["ic"]
    m = re.search(r"(\d+(?:\.\d+)?)\s*A\b", ic.part.description)
    v, _ = buck_vout(ic, row["net"])
    if not m or not v:
        return None, ""
    i = float(m.group(1))
    p = i * v + sum(x[2] for x in POWER_ESTIMATE[1:])
    return p, (f"{ic.ref} {ic.value} rated {f(i, 1)} A x {f(v, 2)} V = {f(i * v, 2)} W on VDD_HP "
               f"+ {f(sum(x[2] for x in POWER_ESTIMATE[1:]), 2)} W 3.3 V-side high estimate")


def _tile_alignment() -> tuple[int, int]:
    tv = bs.THERMAL_VIA
    g, pitch, pad = tv["grid"], tv["pitch_mm"], tv["pad_mm"]
    pos = [(i - (g - 1) / 2) * pitch for i in range(g)]
    nt = round((p4.EPAD_SIZE_MM - p4.EPAD_TILE_MM) / p4.EPAD_TILE_PITCH_MM) + 1
    tiles = [(j - (nt - 1) / 2) * p4.EPAD_TILE_PITCH_MM for j in range(nt)]
    inside = sum(1 for p in pos if any(abs(p - c) + pad / 2 <= p4.EPAD_TILE_MM / 2 + 1e-9 for c in tiles))
    return inside ** 2, g * g


def _thermal_section() -> list[str]:
    tm = thermal_model()
    tv = bs.THERMAL_VIA
    hs = bs.HEATSINK
    exempt = [c for c in bs.COMPONENTS if bs.is_keepout_exempt(c) and c.ref != "U1"
              and ((isinstance(c.place, bs.Near) and c.place.ref == "U1") or
                   (board_xy(c) and keepout_clearance(board_xy(c)) < 0))]
    h_max = max((c.part.height_mm for c in exempt), default=0.0)
    h_soc = U1.part.height_mm
    gap_act, gap_rule = h_soc - h_max, h_soc - bs.KEEPOUT_MAX_HEIGHT_MM
    extent = (tv["grid"] - 1) * tv["pitch_mm"] + tv["pad_mm"]
    inside, total = _tile_alignment()
    fans = re.findall(r"(\d+)\s*x\s*(\d+)\s*x\s*(\d+)\s*mm", hs["fan"])
    p_ceil, ceil_how = _power_ceiling()
    L = ["## 1. Heat paths", "",
         md_table(["Path", "Stack", "Key numbers (from the spec)"], [
             ["(a) Top", f"SoC mould top -> {esc(hs['tim'])} -> {f(hs['base_mm'][0], 0)} x {f(hs['base_mm'][1], 0)} "
                         f"x {f(hs['height_mm'], 0)} mm heatsink ({esc(hs['material'])}) -> 5 V PWM fan "
                         "(impinging, radial exhaust over the board)",
              f"SoC seated height {f(h_soc, 2)} mm; tallest part allowed in the keep-out "
              f"{f(bs.KEEPOUT_MAX_HEIGHT_MM, 2)} mm (rule) / {f(h_max, 2)} mm (actual, {len(exempt)} x 0402 passives around U1) "
              f"-> air gap under the heatsink base >= {f(gap_act, 2)} mm ({f(gap_rule, 2)} mm by rule), "
              f"{f(gap_act + tm['tim_mm'], 2)} mm with the uncompressed TIM"],
             ["(b) Bottom", f"EPAD {f(p4.EPAD_SIZE_MM, 1)} mm -> {tv['grid']}x{tv['grid']} vias "
                            f"{f(tv['drill_mm'], 2)}/{f(tv['pad_mm'], 2)} mm @ {f(tv['pitch_mm'], 1)} mm (VIPPO) -> "
                            f"L2 GND plane + {f(SPREADER_MM, 0)} x {f(SPREADER_MM, 0)} mm B.Cu spreader "
                            f"({f(WINDOW_MM, 1)} x {f(WINDOW_MM, 1)} mm exposed window) -> "
                            "optional bottom gap pad / chassis",
              f"array extent {f(extent, 1)} mm inside the {f(p4.EPAD_SIZE_MM, 1)} mm EPAD; fill: {esc(tv['fill'])}"],
         ]), "",
         f"The heatsink sits flush on the SoC lid: nothing inside the {f(2 * KO, 0)} x {f(2 * KO, 0)} mm keep-out "
         f"is taller than {f(h_max, 2)} mm, so the base clears every 0402 by >= {f(gap_act, 2)} mm. Black "
         "anodising is not a guaranteed insulator -- the gap is the insulation, and the 4-point spring "
         "clamp keeps the base parallel to the board.", "",
         f"Assembly is double-sided: {len(bs.bottom_side_refs())} decoupling caps "
         f"({', '.join(bs.bottom_side_refs())}) sit on the bottom under the SoC's right-hand pad ring, "
         "outside the thermal-via field. So only the via field is left mask-free "
         f"({f(WINDOW_MM, 1)} x {f(WINDOW_MM, 1)} mm, `BOTTOM_THERMAL_WINDOW_MM`); the rest of the "
         f"{f(SPREADER_MM, 0)} x {f(SPREADER_MM, 0)} mm spreader copper (`BOTTOM_SPREADER_MM`) is under solder "
         "mask. A bottom gap pad or bracket must clear those 0402s (<= 0.55 mm) or be cut to the window.", "",
         "### 1.1 Via-array thermal resistance", "",
         "```text",
         f"barrel area  A = pi/4 * (d^2 - (d - 2t)^2) = pi/4 * ({f(tm['d'], 3)}^2 - {f(tm['d'] - 2 * tm['t'], 3)}^2)"
         f" = {tm['a_ring']:.5f} mm^2",
         f"one via      R = L / (k * A) = {f(tm['L'], 2)}e-3 m / ({f(K_CU, 0)} W/m.K * {tm['a_ring']:.5f}e-6 m^2)"
         f" = {f(tm['r_via'], 1)} K/W",
         f"array        R = {f(tm['r_via'], 1)} / {tm['n']} = {f(tm['r_arr'], 2)} K/W   (plating t = {f(PLATING_UM, 0)} um,"
         f" L = board thickness)",
         f"L1 -> L2 only ({f(tm['l12'], 3)} mm of the {f(tm['L'], 2)} mm): {f(tm['r_l12'], 2)} K/W  "
         "(heat reaches the GND plane almost for free)",
         f"solid-copper-filled vias would give {f(tm['r_arr_cu'], 2)} K/W (resin fill k ~0.3-1 W/m.K adds nothing)",
         "```", "",
         f"Constriction in the planes, voids under the EPAD and the resin fill are ignored, so treat "
         f"{f(tm['r_arr'], 1)} K/W as the via contribution only.", "",
         f"EPAD tile alignment (computed): {inside} of {total} via pads fall fully inside one of the "
         f"{f(p4.EPAD_TILE_MM, 1)} mm EPAD tiles ({f(p4.EPAD_TILE_PITCH_MM, 1)} mm pitch); the other {total - inside} "
         "straddle the 0.6 mm inter-tile gaps. If the footprint copper is tiled (not one solid pad), either "
         "merge the F.Cu to a solid 7.5 mm pad (paste stays tiled) or move the array onto the tile pitch.", "",
         "## 2. Power estimate", "",
         "Espressif does not publish a theta-JC, theta-JB or maximum package dissipation for the ESP32-P4 in "
         "the documents used for this design (datasheet, hardware design guidelines, KiCad library). Every "
         "power and package number below is an **engineering estimate** to be replaced by a measurement on "
         "the first build (VBUS power with peripherals off vs. full load, IR camera / thermocouple on the lid).", "",
         md_table(["Contributor", "Low (W)", "High (W)", "Assumption"],
                  [[esc(a), f(lo, 2), f(hi, 2), esc(b)] for a, lo, hi, b in POWER_ESTIMATE] +
                  [["**SoC total (estimate)**", f"**{f(tm['p_lo'], 2)}**", f"**{f(tm['p_hi'], 2)}**", ""],
                   ["Thermal design point", "", f"**{f(P_DESIGN_W, 1)}**", "estimate + margin for unknowns"]] +
                  ([["Hard ceiling (not expected)", "", f(p_ceil, 2), esc(ceil_how)]] if p_ceil else []),
                  "lrrl"), "",
         "## 3. Thermal network (estimate)", "",
         md_table(["Element", "Value", "Basis"], [
             ["theta-JC top (die -> mould top)", f"{f(THETA_JC_TOP, 1)} K/W", "estimate for a 10 x 10 mm QFN mould cap"],
             ["theta-JC bottom (die -> EPAD)", f"{f(THETA_JC_BOT, 1)} K/W", "estimate (exposed-pad QFN)"],
             ["TIM", f"{f(tm['r_tim'], 2)} K/W", f"{f(tm['tim_mm'], 2)} mm / ({f(K_TIM, 1)} W/m.K x "
                                                  f"{f(tm['body'], 0)} mm^2 lid)"],
             ["EPAD solder", f"{f(tm['r_solder'], 3)} K/W", f"{f(SOLDER_UM, 0)} um SAC, {PASTE_COVERAGE:.0%} coverage"],
             ["Via array", f"{f(tm['r_arr'], 2)} K/W", "section 1.1"],
             ["Heatsink theta-SA, fan", f"{f(tm['th_fan'], 1)} K/W",
              f"{PIN_GRID}x{PIN_GRID} pins {f(PIN_SIDE_MM, 1)} mm, {f(tm['fin_h'], 0)} mm tall -> "
              f"A = {f(tm['a_hs'], 0)} mm^2; h = {f(H_FAN, 0)} W/m^2.K, eta = {f(FIN_EFF_FAN, 2)}"],
             ["Heatsink theta-SA, natural", f"{f(tm['th_nat'], 1)} K/W", f"h = {f(H_NAT, 0)} W/m^2.K, eta = {f(FIN_EFF_NAT, 2)}"],
             ["Board -> air, fan exhaust", f"{f(tm['r_bd_fan'], 1)} K/W",
              f"2 x board area, {BOARD_SPREAD_EFF:.0%} effective, top h = {f(H_BOARD_EXHAUST, 0)}"],
             ["Board -> air, natural", f"{f(tm['r_bd_nat'], 1)} K/W", f"h = {f(H_NAT, 0)} W/m^2.K"],
             ["Optional gap pad to chassis", f"{f(tm['r_gap'], 2)} K/W + chassis",
              f"{f(GAP_PAD_MM, 1)} mm, {f(K_GAP_PAD, 1)} W/m.K on the {f(WINDOW_MM, 1)} mm exposed window"],
         ], "lrl"), "",
         md_table(["Scenario", "R top (K/W)", "R bottom (K/W)", "R j-a (K/W)", "Share via EPAD",
                   f"dT j-a @ {f(tm['p_hi'], 2)} W", f"dT j-a @ {f(P_DESIGN_W, 1)} W",
                   f"Tj @ {f(P_DESIGN_W, 1)} W, Ta {f(T_AMB, 0)} C", f"dT across vias @ {f(P_DESIGN_W, 1)} W"],
                  [[esc(s["name"]), f(s["r_top"], 1), f(s["r_bot"], 1), f(s["r_ja"], 1), f"{s['share_bot']:.0%}",
                    f"{f(s['r_ja'] * tm['p_hi'], 1)} K", f"{f(s['r_ja'] * P_DESIGN_W, 1)} K",
                    f"{f(T_AMB + s['r_ja'] * P_DESIGN_W, 0)} C",
                    f"{f(P_DESIGN_W * s['share_bot'] * tm['r_arr'], 1)} K"] for s in tm["scen"]],
                  "lrrrrrrrr"), "",
         f"Reading: with only the via array and the board (no heatsink) the SoC would run roughly "
         f"{f(tm['scen'][2]['r_ja'] * P_DESIGN_W, 0)} K above ambient at the {f(P_DESIGN_W, 1)} W design point; the "
         f"heatsink + fan cut that to ~{f(tm['scen'][0]['r_ja'] * P_DESIGN_W, 0)} K and the via array still carries "
         f"about {tm['scen'][0]['share_bot']:.0%} of the heat. The temperature drop across the via array itself is only "
         f"~{f(P_DESIGN_W * tm['scen'][0]['share_bot'] * tm['r_arr'], 1)} K. With theta-JC(top) at a pessimistic 20 K/W "
         f"the fan-on R j-a becomes "
         f"{f(1 / (1 / (20.0 + tm['r_tim'] + tm['th_fan']) + 1 / tm['scen'][0]['r_bot']), 1)} K/W.", "",
         "### 3.1 Heatsink and fan selection", "",
         md_table(["Choice", "Rationale"], [
             ["Base = keep-out", f"{f(hs['base_mm'][0], 0)} x {f(hs['base_mm'][1], 0)} mm base covers the "
                                 f"{f(2 * KO, 0)} x {f(2 * KO, 0)} mm keep-out exactly; everything under it is <= "
                                 f"{f(h_max, 2)} mm"],
             ["Height", f"{f(hs['height_mm'], 0)} mm keeps the fan top low; the fan shadow is the fan footprint "
                        f"(up to {max(int(x[0]) for x in fans) if fans else '?'} mm square, see section 6)"],
             ["Pin fins", "an impinging fan exhausts radially only through pin (or cross-cut) fins; plate fins "
                          "would dump all flow along two sides"],
             ["Fan", esc(hs["fan"]) + "; 5 V from VSYS through the high-side switch; typically 0.3-0.6 W for "
                     "this size (check the fan datasheet)"],
             ["Clamp", esc(hs["clamp"]) + "; plated holes tied to GND bond the heatsink to ground"],
             ["Margin", f"theta-SA falls from ~{f(tm['th_nat'], 0)} to ~{f(tm['th_fan'], 0)} K/W with the fan "
                        "(estimate; use the vendor theta-vs-airflow curve for the final part)"],
         ]), ""]
    return L


def _mechanical_section() -> list[str]:
    x0, y0, x1, y1 = bs.BOARD_OUTLINE
    L = ["## 4. Mechanical coordinates", "",
         "Design origin = U1 body centre; KiCad axes (+X right, +Y down); mm. Part coordinates are the "
         "footprint origin (for pin headers that is pin 1, not the body centre).", "",
         md_table(["Feature", "Coordinates", "Size / notes"], [
             ["Board outline", f"{xy((x0, y0))} .. {xy((x1, y1))}",
              f"{f(x1 - x0, 0)} x {f(y1 - y0, 0)} mm, R{f(bs.BOARD_CORNER_R, 1)} corners"],
             ["Heatsink keep-out", ", ".join(xy((sx * KO, sy * KO)) for sy in (-1, 1) for sx in (-1, 1)),
              f"{f(2 * KO, 0)} x {f(2 * KO, 0)} mm, max part height {f(bs.KEEPOUT_MAX_HEIGHT_MM, 2)} mm"],
             *[[f"{r} (heatsink, {COMP[r].part.value})", xy(p), f"keep-out radius {f(R_HOLE, 1)} mm"]
               for r, p in bs.HEATSINK_HOLES.items()],
             *[[f"{r} (board, {COMP[r].part.value})", xy(p), esc(COMP[r].part.description)]
               for r, p in bs.BOARD_HOLES.items()],
             *[[r, xy(p), "fiducial"] for r, p in bs.FIDUCIALS.items()],
         ]), ""]
    holes = bs.HEATSINK_HOLES
    rows = []
    for c in placed_parts():
        p = board_xy(c)
        near_h = min(holes, key=lambda h: dist(p, holes[h]))
        dh = dist(p, holes[near_h])
        edge = {"bottom": y1 - p[1], "top": p[1] - y0, "right": x1 - p[0], "left": p[0] - x0}
        e = f"{c.place.faces}: {f(edge[c.place.faces], 1)}" if c.place.faces else f"{f(min(edge.values()), 1)}"
        rows.append([c.ref, esc(c.value), xy(p), f(c.place.rot, 0), f(c.part.height_mm, 2),
                     f(keepout_clearance(p), 1), f"{near_h} {f(dh, 1)}", e,
                     status(dh >= HS_FLAG_MM, warn=dh >= R_HOLE)])
    L += ["### 4.1 Every absolutely placed part", "",
          md_table(["Ref", "Value", "x, y", "Rot", "Height (mm)", "Clearance to keep-out (mm)",
                    "Nearest M2.5 hole (mm)", "Board-edge dist (mm)", "Hole check"], rows, "llrrrrlll"), ""]
    return L


def _collision_section() -> list[str]:
    holes = bs.HEATSINK_HOLES
    conns = [c for c in placed_parts() if c.part.kind == "conn"]
    links = hs_links()
    L = ["## 5. Collision check (M2.5 heatsink holes)", "",
         f"Flag thresholds: a part origin closer than {f(R_HOLE, 1)} mm (`HEATSINK_HOLE_KEEPOUT_R`) to a hole "
         f"centre is a **FAIL**; a high-speed corridor closer than {f(HS_FLAG_MM, 1)} mm (keep-out + 1 mm) is "
         "flagged. HS corridors are approximated as the straight segment from the centroid of the SoC pad "
         "group (`pad_position`) to the connector / device placement.", ""]
    # (i) + summary
    summ = []
    for h, hp in holes.items():
        dk = keepout_clearance(hp)
        cn = min(conns, key=lambda c: dist(hp, board_xy(c)))
        dc = dist(hp, board_xy(cn))
        pp = min(placed_parts(), key=lambda c: dist(hp, board_xy(c)))
        dpp = dist(hp, board_xy(pp))
        hl = min(links, key=lambda l: seg_dist(hp, l["a"], l["b"]))
        dl = seg_dist(hp, hl["a"], hl["b"])
        ok = dk >= R_HOLE and dpp >= R_HOLE and dl >= HS_FLAG_MM
        summ.append([h, xy(hp), f(dk, 2), f"{cn.ref} {f(dc, 1)}", f"{pp.ref} {f(dpp, 1)}",
                     f"{esc(hl['label'])} {f(dl, 1)}", status(ok)])
    L += ["### 5.1 Summary per hole", "",
          md_table(["Hole", "x, y", "(i) to keep-out (mm)", "(ii) nearest connector (mm)",
                    "nearest placed part (mm)", "(iii) nearest HS corridor (mm)", "Status"], summ, "llrllll"), "",
          f"(i) The hole keep-out circle (r = {f(R_HOLE, 1)} mm) clears the keep-out corner by "
          f"{f(min(keepout_clearance(p) for p in holes.values()) - R_HOLE, 2)} mm.", ""]
    # (ii) hole x connector
    rows = []
    for c in conns:
        p = board_xy(c)
        cells = []
        for h, hp in holes.items():
            d = dist(p, hp)
            cells.append(f(d, 1) if d >= HS_FLAG_MM else f"**{f(d, 1)}**")
        rows.append([c.ref, esc(c.value), xy(p), f(c.part.height_mm, 1), *cells])
    L += ["### 5.2 (ii) Hole centre -> connector placement (mm)", "",
          md_table(["Connector", "Value", "x, y", "Height", *holes], rows, "lllr" + "r" * len(holes)), ""]
    # (iii) hole x HS corridor
    rows = []
    for l in links:
        cells = []
        for h, hp in holes.items():
            d = seg_dist(hp, l["a"], l["b"])
            cells.append(f(d, 1) if d >= HS_FLAG_MM else f"**{f(d, 1)}**")
        worst = min(seg_dist(hp, l["a"], l["b"]) for hp in holes.values())
        src = f"U1 pads {ranges(l['pads'])}" if l["pads"] else l["from"]
        rows.append([esc(l["label"]), src, xy(l["a"]), f"{l['to']} {xy(l['b'])}", f(dist(l["a"], l["b"]), 1),
                     *cells, "OK" if worst >= HS_FLAG_MM else "**route around**"])
    L += ["### 5.3 (iii) Hole centre -> straight-line HS corridor (mm)", "",
          md_table(["Interface", "From", "Start", "To", "Length", *holes, "Status"], rows,
                   "llllr" + "r" * len(holes) + "l"), ""]
    flagged = [r[0] for r in rows if r[-1] != "OK"]
    if flagged:
        L += [f"Flagged corridors ({', '.join(flagged)}): the straight line passes inside the hole keep-out "
              "+ 1 mm; route these pairs around the standoff (keep the pair symmetric and on L1 over L2) or "
              "move the connector.", ""]
    # other parts
    fails = []
    for c in placed_parts():
        p = board_xy(c)
        for h, hp in holes.items():
            if dist(p, hp) < HS_FLAG_MM:
                fails.append([c.ref, esc(c.part.package), f(c.part.height_mm, 2), xy(p), h, f(dist(p, hp), 2),
                              status(dist(p, hp) >= HS_FLAG_MM, warn=dist(p, hp) >= R_HOLE)])
    near = []
    for c in sorted(bs.COMPONENTS, key=lambda c: natural_key(c.ref)):
        if not isinstance(c.place, bs.Near):
            continue
        an = near_anchor(c)
        if not an:
            continue
        for h, hp in holes.items():
            lb = dist(an[0], hp) - an[1]
            if lb < HS_FLAG_MM:
                near.append([c.ref, esc(c.value), esc(c.part.package), an[2], f(an[1], 1), h,
                             f(dist(an[0], hp), 1), f(lb, 1), "possible intrusion" if lb < R_HOLE else "tight"])
    L += ["### 5.4 Other parts vs the hole keep-out", "",
          md_table(["Ref", "Package", "Height", "x, y", "Hole", "Distance", "Status"], fails) if fails
          else "No absolutely placed part within the flag distance.", "",
          "Relatively placed parts (`Near`) whose worst-case position (anchor distance minus the allowed "
          "`max_mm`) can reach a hole keep-out -- constrain these in the placer:", "",
          md_table(["Ref", "Value", "Package", "Anchor", "max_mm", "Hole", "Anchor dist", "Lower bound",
                    "Status"], near) if near else "None.", ""]
    # board holes + fiducials
    rows = []
    for h, hp in bs.BOARD_HOLES.items():
        pp = min(placed_parts(), key=lambda c: dist(hp, board_xy(c)))
        d = dist(hp, board_xy(pp))
        rows.append([h, xy(hp), f"{pp.ref} {f(d, 1)}", status(d >= M3_KEEPOUT_R + 1.0, warn=d >= M3_KEEPOUT_R)])
    for fid, fp in bs.FIDUCIALS.items():
        pp = min(placed_parts(), key=lambda c: dist(fp, board_xy(c)))
        d = dist(fp, board_xy(pp))
        rows.append([fid, xy(fp), f"{pp.ref} {f(d, 1)}", status(d >= FIDUCIAL_CLEAR_MM)])
    L += ["### 5.5 Board holes and fiducials vs the nearest part origin", "",
          f"Assumed clear radius: M3 washer {f(M3_KEEPOUT_R, 1)} mm (+1 mm margin); fiducial "
          f"{f(FIDUCIAL_CLEAR_MM, 1)} mm (1 mm copper dot + mask opening + camera margin).", "",
          md_table(["Feature", "x, y", "Nearest part origin (mm)", "Status"], rows), ""]
    return L


def _airflow_section() -> list[str]:
    hs = bs.HEATSINK
    fans = [int(a) for a, _, _ in re.findall(r"(\d+)\s*x\s*(\d+)\s*x\s*(\d+)\s*mm", hs["fan"])]
    shadow = max(fans + [int(hs["base_mm"][0])]) / 2
    tall = hs["height_mm"] / 2
    near_z, far_z = 0.6 * hs["base_mm"][0], 1.2 * hs["base_mm"][0]
    rows = []
    for c in placed_parts():
        p = board_xy(c)
        heat = c.part.kind in ("ic", "ind") or (c.part.kind == "diode" and {n for _, n in c.part.pins} == {"A", "K"})
        if not (heat or c.part.height_mm >= tall):
            continue
        cl = keepout_clearance(p)
        zone = "near exhaust" if cl <= near_z else ("far exhaust" if cl <= far_z else "outside")
        in_shadow = abs(p[0]) < shadow and abs(p[1]) < shadow
        role = "tall" if c.part.height_mm >= tall else "heat source"
        verdict = ("**in fan shadow**" if in_shadow and c.part.height_mm >= tall
                   else ("OK" if role == "tall" and not in_shadow else zone))
        rows.append([c.ref, esc(c.value), role, f(c.part.height_mm, 2), xy(p), direction(p), f(cl, 1),
                     "yes" if in_shadow else "no", verdict])
    L = ["## 6. Airflow", "",
         "The fan blows down into the pin fins; air leaves the fin field radially at board level and sweeps "
         "the top copper. Rules applied: parts taller than half the heatsink height "
         f"({f(tall, 1)} mm) stay outside the fan shadow (largest fan option, +/-{f(shadow, 1)} mm); heat "
         f"sources should sit in the near exhaust (<= {f(near_z, 0)} mm from the keep-out edge) or far "
         f"exhaust (<= {f(far_z, 0)} mm). Zones are geometric estimates, not CFD.", "",
         md_table(["Ref", "Value", "Role", "Height", "x, y", "Direction", "Clearance to keep-out",
                   "In fan shadow", "Verdict"], rows, "lllrllrll"), ""]
    return L


def _fan_section() -> list[str]:
    hdr = next((c for c in bs.COMPONENTS if {"PWM", "TACH"} <= {n for _, n in c.part.pins}), None)
    if not hdr:
        return ["## 7. Fan control", "", "No 4-wire fan header found in the spec.", ""]
    pwm_od, tach_raw = net_of(hdr, "PWM"), net_of(hdr, "TACH")
    vfan = next(n for p, n in hdr.conns.items() if pin_name(hdr, p) not in ("GND", "PWM", "TACH"))
    q_pwm = next((c for c, pad in members(pwm_od) if c.part.kind == "fet" and pin_name(c, pad) == "D"), None)
    g_net = net_of(q_pwm, "G") if q_pwm else None
    r_g = next((c for c, pad in members(g_net or "") if c.part.kind == "res" and other_end(c, pad) in USE_BY_NET), None)
    pwm_net = next((n for n in r_g.conns.values() if n in USE_BY_NET), None) if r_g else None
    r_pd = resistors_between(g_net, GND) if g_net else []
    r_pu_od = resistors_between(pwm_od, vfan)
    q_hs = next((c for c, pad in members(vfan) if c.part.kind == "fet" and pin_name(c, pad) == "D"), None)
    hs_g = net_of(q_hs, "G") if q_hs else None
    hs_s = net_of(q_hs, "S") if q_hs else None
    r_hs = resistors_between(hs_g, hs_s) if hs_g else []
    q_drv = next((c for c, pad in members(hs_g or "") if c.part.kind == "fet" and pin_name(c, pad) == "D"), None)
    en_net = net_of(q_drv, "G") if q_drv else None
    r_en = [c for c, pad in members(en_net or "") if c.part.kind == "res" and other_end(c, pad) in RAILS]
    r_tpu = [c for c, pad in members(tach_raw) if c.part.kind == "res" and other_end(c, pad) in RAILS]
    r_tser = [c for c, pad in members(tach_raw) if c.part.kind == "res" and other_end(c, pad) in USE_BY_NET]
    tach_net = other_end(r_tser[0], next(p for p, n in r_tser[0].conns.items() if n == tach_raw)) if r_tser else None
    g_pwm, g_en, g_tach = gpio_of_net(pwm_net), gpio_of_net(en_net), gpio_of_net(tach_net)

    def rv(cs):
        return ", ".join(f"{c.ref} {c.value}" + (" (DNP)" if c.dnp else "") for c in cs) or "?"

    rows = [
        ["PWM (open drain)", f"{q_pwm.ref if q_pwm else '?'} {q_pwm.value if q_pwm else ''}; gate {rv([r_g] if r_g else [])}; "
                             f"pull-down {rv(r_pd)}; optional pull-up {rv(r_pu_od)}",
         f"GPIO{g_pwm} {code(pwm_net)} -> {hdr.ref}.PWM {code(pwm_od)}",
         f"GPIO floats at reset -> {rv(r_pd)} holds the FET off -> the fan's own pull-up reads 100 % duty"],
        ["Fan power (high side)", f"{q_hs.ref if q_hs else '?'} {q_hs.value if q_hs else ''} from {code(hs_s)}; gate pull-up "
                                  f"{rv(r_hs)}; driver {q_drv.ref if q_drv else '?'} {q_drv.value if q_drv else ''}",
         f"GPIO{g_en} {code(en_net)}",
         f"{rv(r_en)} pulls {code(en_net)} high -> driver on -> fan powered at reset; low = zero-RPM"],
        ["Tach", f"pull-up {rv(r_tpu)}; series {rv(r_tser)}", f"{hdr.ref}.TACH -> GPIO{g_tach} {code(tach_net)}",
         "input; count falling edges in PCNT (2 pulses / rev)"],
    ]
    curve = []
    for lo, hi, (d0, d1) in FAN_CURVE:
        rng = (f"< {f(hi, 0)} C (off again below {f(hi - FAN_HYST_K, 0)} C)" if lo is None
               else (f">= {f(lo, 0)} C" if hi is None else f"{f(lo, 0)}-{f(hi, 0)} C"))
        duty = f"{d0} %" if d0 == d1 else f"{d0} -> {d1} % (linear)"
        ledc = "don't care" if d1 == 0 else (f"{100 - d0} %" if d0 == d1 else f"{100 - d0} -> {100 - d1} %")
        curve.append([rng, duty, ledc, "low (fan unpowered)" if d1 == 0 else "high"])
    curve.append(["sensor error / tach fault", "100 %", "0 %", "high + raise alarm"])
    L = ["## 7. Fan control", "",
         f"{hdr.ref} {esc(hdr.part.description)}. Intel 4-wire PWM fan spec: 25 kHz nominal (21-28 kHz), the "
         "PWM input is driven open-collector/open-drain against the fan's internal pull-up, an open or "
         "high input means full speed, tach is open-collector with 2 pulses per revolution.", "",
         md_table(["Function", "Parts (netlist)", "Signal path", "Reset / fail-safe"], rows), "",
         "Fail-safe chain: any reset, brown-out, crash-induced watchdog reset or unflashed board leaves the "
         "fan GPIOs floating, so the fan is powered and at 100 %. Firmware only ever *reduces* cooling.", "",
         f"### 7.1 Suggested firmware fan curve (P4 internal temperature sensor, {f(FAN_HYST_K, 0)} K hysteresis)", "",
         md_table(["Die temperature", "Fan duty", f"LEDC duty on GPIO{g_pwm} (inverted by {q_pwm.ref if q_pwm else '?'})",
                   f"GPIO{g_en} FAN_EN"], curve), "",
         "Starting values only -- retune once the thermal numbers in section 3 are measured. Update once per "
         "second, slew-limit the duty (~5 %/s) to avoid audible hunting, and treat a tach reading below "
         "~300 RPM for 3 s while duty >= 30 % as a stalled fan (force 100 %, flag an error).", "",
         "```c",
         "// ESP-IDF sketch -- GPIO numbers generated from board_spec.GPIO_MAP",
         f"#define FAN_PWM_GPIO  {g_pwm}   // LEDC, 25 kHz; output inverted by the open-drain FET",
         f"#define FAN_TACH_GPIO {g_tach}  // PCNT, falling edges, glitch filter ~1 us",
         f"#define FAN_EN_GPIO   {g_en}  // high = fan powered (board default via pull-up)",
         "temperature_sensor_handle_t ts;               // driver/temperature_sensor.h",
         "temperature_sensor_config_t tcfg = TEMPERATURE_SENSOR_CONFIG_DEFAULT(20, 100);",
         "temperature_sensor_install(&tcfg, &ts); temperature_sensor_enable(ts);",
         "for (;;) {",
         "    float t; int duty = 100;                  // fail-safe default",
         "    if (temperature_sensor_get_celsius(ts, &t) == ESP_OK) duty = fan_curve(t);  // table above",
         "    if (tach_stalled(duty)) duty = 100;",
         "    gpio_set_level(FAN_EN_GPIO, duty > 0);",
         "    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, ((100 - duty) * LEDC_MAX) / 100);",
         "    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);",
         "    vTaskDelay(pdMS_TO_TICKS(1000));",
         "}",
         "```", ""]
    return L


def render_task2() -> str:
    L = [BANNER, "", "# TASK 2: Mechanical & thermal strategy", "",
         "All coordinates, dimensions and part data are read from `hardware/lib/board_spec.py` at generation "
         "time. Thermal values are estimates with every assumption listed next to its result.", ""]
    L += _thermal_section()
    L += _mechanical_section()
    L += _collision_section()
    L += _airflow_section()
    L += _fan_section()
    return "\n".join(L).rstrip() + "\n"


# ===========================================================================
# Driver
# ===========================================================================

def outputs() -> dict[Path, str]:
    return {TASK1_MD: render_task1(), TASK2_MD: render_task2(), TASK4_MD: render_task4(),
            BOM_CSV: render_bom_csv()}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if a generated file is missing or stale")
    args = ap.parse_args(argv)
    stale = []
    for path, text in outputs().items():
        rel = path.relative_to(ROOT)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print(f"up to date  {rel}")
            continue
        if args.check:
            stale.append(rel)
            print(f"STALE       {rel}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote       {rel}")
    if stale:
        print("run `python3 -m tools.gen_docs` to regenerate", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
